const express = require('express');
const fetch = require('node-fetch');
const nodemailer = require('nodemailer');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  AlignmentType, BorderStyle, WidthType, ShadingType, Header, Footer, PageNumber, ImageRun
} = require('docx');

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const {
  FIREFLIES_API_KEY,
  ANTHROPIC_API_KEY,
  GMAIL_USER,
  GMAIL_APP_PASSWORD,
  NOTIFY_EMAIL,
  CLAUDE_MODEL = 'claude-opus-4-5',
  TRACKER_WEBHOOK_URL,
  ACCESS_TOKEN = 'option10audit'
} = process.env;

// ── Option 10 logo (base64 embedded for Railway deployment) ──────────────────
const LOGO_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAacAAADGCAYAAAB2ME/TAAAAmmVYSWZNTQAqAAAACAAGARIAAwAAAAEAAQAAARoABQAAAAEAAABWARsABQAAAAEAAABeASgAAwAAAAEAAgAAATEAAgAAABUAAABmh2kABAAAAAEAAAB8AAAAAAAAAEgAAAABAAAASAAAAAFQaXhlbG1hdG9yIFBybyAyLjMuOAAAAAKgAgAEAAAAAQAAAaegAwAEAAAAAQAAAMYAAAAAOTjs9QAAAAlwSFlzAAALEwAACxMBAJqcGAAAA25pVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MTk4PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjQyMzwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+UGl4ZWxtYXRvciBQcm8gMi4zLjg8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgICAgPHhtcDpNZXRhZGF0YURhdGU+MjAyMy0xMS0yNlQxMjo0MzoyOC0wNTowMDwveG1wOk1ldGFkYXRhRGF0ZT4KICAgICAgICAgPHRpZmY6WFJlc29sdXRpb24+NzIwMDAwLzEwMDAwPC90aWZmOlhSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpSZXNvbHV0aW9uVW5pdD4yPC90aWZmOlJlc29sdXRpb25Vbml0PgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjAwMDAvMTAwMDA8L3RpZmY6WVJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgrFpkNxAAAgAElEQVR4nOydeZhT1fnHv++5SWZltgyLymZVrFrBOgoOk9y468+tLgW3WpEZQJhhEdcutlNtq63KOgMCM4BV64JatVp3JcnAgBR33JDKIsoymYXZk9z7/v6Y0CImk5vlJhm4n+eZh4fcc8/75t6c+95zzrsABgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGhxmUbAUMDAwMUoGyqqafMZR5RDT8vx8yr66pKDwraUodxhjGycDA4LBn4oKmUSTU1UTIO/gYkThz2bR8ZzL0OpwRyVbAwMDAINkISV0ZzDAxo5kk/iAZOh3uGMbJwMDgsKas2vN7AKcEPUh4fumUgpbEamQAGMbJwMDgMIcZs0IeU8S8ROpi8D8M42RgYHDYUlrVcGOw5TwAAPPq5TPyP0ywSgYBDONkYGBwOFMZ+pBkzJqSiCnZChgYGBgkg55ZEw0PdoyZt9ZW5L+QWI0MDsSYORkYGBx2TF7SmIteZ029HjNIAIZxMjAwOOxQ/Tyr91lT4SOJ1cjgYAzjZGBgcNjRm4cejFlTSmAYJwMDg8OK3jz0jFlT6tCnHCLKFngGQ+LRgBjBzMcR4TiVub8AZYOQBSAbzH4G2kDUSlDbWBU7iLAZoC9J0Kfp/rx1C2dQd7K/i0HsTF3UnN+tKucRcDIRjgFwNBgDQZwFIJsZJhAaibEXwF6AGgDeC6K9zPSFqprfWjGj394kfw2DIHTOSh/+ZYbt5ypMY9K4fUSW0nSkRe3KNqPLZFY7JQt3kUomdFMmeylD9YoMf4s0oGuf1H93u6nwq2bTwPffy7niH/fPOPk9EPFB3VeGkkuQeptRGSSQlM6td8MDnGXJaLqUwGepYFmARjDFpjOBO8FYByKXwvzqiorC9fHS10Bfxj3NltzdLTYI/3nMdDYRfsoxvGARQ2HijwFyEYt3OlX1ncdnWPfFU2cDbfBk5G7NO+Umn7CMz/XtOjlf2Z0da5/dlInt6Sd7d5qP37wt7af/2lB4TZXq55sQyjgZSV5TipQzTpWVLHb0bzyfwNcz4zIQ9dNTHjN/IYiehCr9rWZ63td6yjKIjkkLPRew4KnMOEvX3wOzj4jWg2hpS2H+E6vGk6KbLAPwOEi7hwz/ebfU79ZC37ZTzeiW9JT3abqMqiFPhjxuJHhNLVLGOE1fwGmdwlPGwC0g+lESVFAJ/BKI7q+ZZl2XBPlhKVvkuQkqVwPcDqJtDKxniLVQxReqmVrIK5rb/Nltq2ZTZ7J1jZXJS9isKo2/YObpAAXPe6YnzNtAYrFkwpK+lluNKyH27Rs4d/axm3bVTiu8L9n6HAxPRuaenOF3pCkdszO5RdeXzwOZd9QqfJlZEkKp1Jg1TV7SOFTxqU4i+jcD66FS/b6B+RtWjSdvsnUDgLIqjxJ29Ypwde0066pYZSV9z2nc02zJ3ds4vZMbZzHRUUlURTDoMlJxaenChjcBcU/t9II1SdQnKEyUDlA6ACuAUwk8FUKBpACQgBypEWVVDV0M7AZoNxHvAtNuEG9XVdNry6fn/TvJX6FXSmtaCqjbN1X1Nd7MhKOS9v5ENAzg+1U/7iqt9qwEi/m1FfnbkqOMdrgSoq2l4CmV6HKolFJBpHwLMvbS0N/v447p+f7vMhMp+xvLiaENEwCQtDBx2oSBaBgDwwBcBcHI3ePpKq1q+ICIXvdLpsdX3py7OdkqJoKkGqeJ1Z7zaW/jPAZ+nCpzOCYQiM4D+JzSas+jXmG589Gp/fYkW69I6DFgGAZgGIMCz3cCCeXe0qqGbwB6DYJf3tdlfS2VZlllizw3cZfvL0xUmDK/ByAPwCzAX1Za3XhXbXnBomTrFAoeB2lfS/6zGdz+s26R0Gd/WNpn9bu8GZk1eepuazLkf5lZHPLYcR1rMWbfs3/vP+fdP341+PT7Um05NzCez2DgDJPff3dpVcN6Aj0Nf9oTNbOydydbP71Iiiv55CX7Csuq9z4pGK8A+HEydNCAAHCjRen+dGK1Z1KylYkbRINBKAXTc7lpjTvLqj2V1y/w5CRTpYmLmn9UVtXwKjNqQVSYTF1CQiIb4KqyqoZ/TqhuG5RsdQ6Gx0FqHZz/fAZ3/CzZuhwIT8OghtlHrTbD+48sbk6KYQKAzRljQx67pPEhjG19Iu3WnVfee8nmOVtKFzeMTqBqERF4eT6DCXPY1LW9tHrvK6XVnguTrZceJNw4lS5u/Ini965liPGxet4lBKICApaUVXmWTF7C5mSrE08YyGPgdxkSby6tarxz3BzOSKT8ykoWE6s8s0n1v89E5ydSdrQw0cUm7vpgUlXDFcnWZT88GebWwQUvpXPHJcnW5UC8FebT2tLyP8lRGxzJ1uXLEMZpcPcnOK6zHgCQo+zFtXt/Pezq3b+tu7lq9w2J1C8qiMyAuADAv0qrGtZOqmpMqfsfKwk1ThMXNl1GKrsAOjaRcuMBEyapPs/rNyxuHZBsXeINg/qD+L5cS+OXExd6rkqU3G8KG58gwoN6e2TGGyYawKBnSqs8E5OuSyUsbZkFL6dze0q9PXfcknGN35y+Jo07kjZb2s+6fuPQKeUGPTaq7dUffHZm8wrzzTt/+bc75r0/F8yp/wINAERnqMQvllU3vFu6qOHyZKsTDxK251Ra1XgnkXpvLHEp+yFmLzNthsCXAH8F0F5i2gdCK6CaGcghRg4TDSXm49ATHxWzswUTOSxK99qJC5quOhTrvDDhKCI8VVrV8OCQBuuvKytJ1VUg4bP4dMN7AfqWgVEa2v4bjJFMZIlFJhOIiJLqXMLTkdbakv9KOtqT7mW2Hwao9Zb8+4TaeaeIg4OZn9Kw1zRcaTINammTrN8qLH3HwtzkE+bmNH+baqbuHMFKXqa/aVA/tfmoHGVvQbbq+d4Kx8vWW0P2H8w4AcCJnasxfef1s3IemjfyswWeK/pK/BuDTgPjubJqz3qFpfIVFXnvJVunaNHdOE1fwGkdwrMMxL84OEw7EgjYx4w3ifhFv096ceUt+c2RnD9hYePJJsFXMfPFBDo16iVFoh8JSXWWVTdMrCkvfC6qPlIbAaI7dvT3nHbD4tbr9HQG8Uumx01+/91R3QvmdUT0Ggiv1Uy1ri9b3DgBjNqwMlVRKmVIO9Hlv5yILwNwHoMiXs4k8L9rplk/iljvOMG3IKONCl5NV9vlZOlwMHwbsvapA57NUFsuiGXBvkPkYnPGGR3b0kau/aTf+dWbjrL/MxInhZZbckbvTjthVo5vz/kNluFWj3lo0HZW33YM9n4asp+Bvi2o+PaGsx8b8JcPsxY0n7t0Rt6WyL9NcmBgjIC/vqzKM1+YCyqXTqGOZOsUKboap3FzOKNTanwNIFtUHTB3g+hJYvF8hpr3aixph1ZOL/gYwMcAKicsbhouFPVKQXwdg06NWC0gh5ieKq1unJnK3luxQWenKd4Nk6o8Fy2rsG7SQ8LKm3M3l1Y1rAfoDE0nMPuI+B8K09zvZfaYBmCRR7Pc2rLcRgDLASyfvKT9CNXfdSszSkEIvvYTVBc8prltnOHJyGxFwZvpantoF7QEw9OR06bk12dwy4nRnO+lDLyfdVH7N+k/+dd7uf83/4HpP10DvAjgjxH3lTt337vA+usAYObC158BEHSpev9eU29kqs0o3VUx/MkBze/5FzTJfWrFhMjMwG2K33NFabVnem25Nfg0MUXR1TjlpjXWMhCNYVIJ6jNCNf9Gj7eVlVPztwKYA+a5pdXNvwCplQCOjqQPJkhgde6khZ4ty6ZbX4u3jqkAE4Yw8OLkJe22pVOyvtNFCNFTAHo1Tj0pp2gpQ5pXUx7fWKPA97qttKblz9TtnwFWy5lEr/skBO7kdHNSjBPfhqxWpeCtdG4fkwz5wWCA2qTcp9O4I2LDpELCxuzLfKvzJi76nM/7zaO3Uzvw67joNXlJY267n0PuoY7oWKupHwk+jN/7+xyPeejLNyxuPbWvhZYAdAwxXi6t8jzq7Swo77nGqY9uDhGlVQ2/ZeCayM/k1SpzSU15/2t0n0YTcW1F/qOZSsGJAN0F5sYIzzerxI9PXLTveJ00jA7mjQA+J1Y9AGLdNzpa8XW+eMMDnBUHzX6AV1ieALMvdAv1VWLLT2sqrLfoGQRbW5bbWFNurRTmtBPAqCVGyGUkBr0cmH0lFJ6G7FalYHUqGSYA6J6V9dc0dF0Q6XmfZci85IgVzyw7ombob247f1a8H5qqn0Mmcc337cAZrdqTGJi5CxN2zTxqWOcnL/RFr90eF3T8Mi2zYW3KPa9CoItxKqtuuJJAv4/kHALvBfGVteWFZyc6GevCGdRdW17wV6SbR4Dxt4hOJiog1fdcoLJmaiCJm2rLrSfWVPTvv6+7oB8TXUyM+QT1Y2JEvvVHVJSW4XmyspLj/nt5dGq/PWB64wcHmLeDcHVtef+LllXkfBlvuaFYOiWnobbCOokIDgIH30wmSnhJBZ6M3H3mfFc6t5+WaNm94Z1hvoFYuS2Sc5qlQagdtPjT6iOfOHHmnVePW1mevUsP3Xqr2SRYndEK6w9/d72Qo+zBhN3Tz0jv+urh2LVLDgxxsmBffVlVU0rFwwUj7g+biQuaRgG0nAmakzgS8ydCMY2tnVb4fLz1iYTastzG2grrBAB3EODXfCLhBMXLj+vx8I6VVbOpc/m0gldqKqy31JT3H6UCNoBfQoQzKia6+Jv+jZV66EgSfT8bJ+OpNLL+JB75uaJlWbl17eC91tHEdCeY/7fXyfzNkD35ryRSF56FvLasAlcGdfw0kXLD4Z1uPkMR5tofVqQIzfa0kVh41GPPfJp506lLpxd+rpduvdVsAvPqv9xy6kLrvG/P9yLzPjUCb/Gh3R/juj13TZy4qGF6vHRNNAzkManPllV77kllV/m4PkxvWNw6gCT1OQa0Zxxg/menSrZU8oSpLbc+yKCrwNCe8FPgoh39G/+io1pxYXmFtb62vPAylaXRYLwb2dl868RFzXFPyiuk/OcI2BdY3rujtsJ67aJyaou3nEiprCS1pqLgARU4sydkAQDwd91d7A+ApyK/lQrq0rh9ZKJkaoFnY4jPlPFPCYrmJa73sy9Rq458/Lf3zraP07umGhEFnTUxo5khTdj//+x5Tb9WQdf4Ye5lafn7nNr+Ei7b++DciYsazo1Z0Whh3o7YluwFA78tXdT4zLinOaawCr2Iq3GyKN3LoNGxgBgM5r/WllsvT8UYgtrygn8qTDKY/6P1HGLM7itR2isq8t6TzAV2AA9B44+cQRnEygPx1iXg5loD4KLacuuD8e4/VlZUFK6XTOJ0Ap6UGCsTJZdvRWFbesGadG4/KVEytdKh9vu7mbs1pZpiCLySP7NrycCaK+bNHPEnvXWbtKjJASBoJnsizDt47zJzfudTJu4u6aZMzfuI/9c0Xzqxzfl0aU1LQYzqRgUBcySVfwJQNViN5UXuitw9nhcnL+HUSsaIOBqn0kUNl4PoUs0nEO6trSi8K0iVypRh5fSCj0mlM4mxU0t7JpBK6pzpCzhNb93iwdIp5Kstt95OwDW9OyX8D2JcPrHaE/dUQzXl1ttqKwrfine/8WLplIKWmnLrdXouRR0IT0f/fUrBmjRuPyER8iLBO8N8g5m9mr1wny+4y/diwV3nLp+e/6Keeu2HVaUy6OfMW2vKrX8Idswy37ch2980WiGLptUSgoqrGu7NN3W23x+DqjGxdHrh57XlBdMlc+bxBF5CzFFFPTPR+arP83Kyc2weTFyM0+QlnAmmh7S2J8aqmnJrZTxk603NDOs3KjCewBqzd9OxHaIxPr6wCaKm3PoMgMnQMINiAhE4aQPycIBnYmCbKX9tBtpHJFuXg+HJyPVR2hytQbb1/a7m16zlkxNVfqa0quFGEJ0Z4nBlb+fSQmwxKZ1XMYSmgN+jvJ/h7OZlpTdVNSTVe3LplKzvasoLpyomOjXypfoemMiRIeG1qYua8+OtX7TExTip/sbboTVOiHmjMBfcFA+5iWJ5hbVeBcq1eroR8W2TlzQGD0tPUWorCh8BSKNRpVMmVTclvgDgYQDPwhGtIr8+jTtSMv+kN93yWzP5NC3nfZU+Gk8X3jN3eXnhSp3VAvBfZ6x5QQ8yr+75jfeOeYH/LWL/LK0+rRc2VQmr/7uUqAW14mbrp/sGFJQQcI/WlZADYWCMj/1vpIrncczGaVo1Z4PVCi1tCfhWJbqyL6bSWF5euJKhBv/hHwSDMhQ/btdbp3hTOy3/ATBrqgKssjJeb30ON7gCR7Yhf106d0QUEJ4o+FYUKsJUrqWtxzQEjwyc93r/pmEJGwdCKPNCeeiRkCq19mOZ76tShGWFlrYZ6j44WlaeniplK1aNJ6Wm3FoJCXZw5LkrGXSq4leeHPc0a/a21ouYjZMXTRXhIuoBgBiKCrpmRbl1R6wyk8WQhsLbwXBra61OSMW6P71CxCpMFZreughXJkCjwwaejSGtpvz1aehI2Rm312+ZaYISNg+hAjOWD6z65htp+LhEeTZOWtTkCLmcx7x62bR8ZyT9pbe3TvGR5WMtbe0tj6Kff/dvIulfb2qnFr67z1twGjFHkV5NXJC711MVf60i1CKWk6cv4DRmVZO/P4OfXl5eUBeLvGRTWUkqJL4dmrzbKMvE3bN1VyrOrKjIe48IGuKLaETZouYi/TU69OFyDGtT89elo2NwsnUJBU9HjkrmGVra1ueMx3/SR9+ZSC/cUE4QQGSzpv+esxQ+i9I5U8vyXqbaAse+x0rKFjXaI5WjJ6tmU2dNRWEFMWb3lvEkGAyaUlbtCZ3OPQHEZJw6RNMVIDoiXDti7mJhujsWWalC7dTCdwnqM1raMqu/SIXpcaQwiSc0tWP1HL11OdThChzdaspfl4aOI5OtS2/4hPlqif1hvbm6KBuvFkz/oLYiX9NvKB70Nmti8PORzpr2Y17gf0chk6a8mWNaVhGp3SlZMbumwjpPJZoQsTcf4/6y6oakrZDEtqxH6nVamjHRw8un5WmOF0p1iNN+p+lGCzGo3+7mixOgUlzZV5j/KsC7NTQdorsyhzA8Hce0m/Pq06lD8/IvQ2CX+biI3oLjgUqWX2jx0Hs7rxSN0tG3JjJEhDn0XrAgSdM+cSgkxXunivBLk4X+7RjRse5KvXJQxsry8oLHmehyAjTPZnuy/FCNHoH3WojaON2wuHUAMcLHuzA3SSbzn6OVk4oEcr3VaGkrSL1eZ3XiTk/tHNKQsplT+m0/leFxkDqlfq9ZuHOg1nNUSHiq8J42ECc0IzrPwnCCEjauqUUaiLfzJ79aMz3v7UToBQCBHHHBPUej2Gs6GMtC34cEelxL29Nbn89Ky0xcJelIqS23vqowX0DMmrOqM5BHqrIiGanZohaYpnSP01JNlIgWLp2S0xCtnJTFn37v93KuhYCJLxo3hyMuZpdsiPFN2EYce3XhwxVaBcWsdN7sh1nTUosCM54YcF/LO3mTHAO7Nn+rt34H4mfT1cThH05v5U/hVlGYWMeAnnI3wQ9FsdcUDAs6f8caZk+j2l+FxOq4eMjUixUVhetZEudGVIGBYP+mv+dXOqoVlKiNE4M0lYZWyZywtedEUjMrezcYrvAtKatfWmptlGqBCRq8Ko2ZUyyYF/rfNKPr//ww9/qS44cFjw/4a2Nd/g22ZJTdVkk6O9ySXk9dpou/SqR+vc6agA9inTXth+ZhK1iEDW7NUpsxrHODI9X3mWunFnxCbBqv5eX6vzDunlTdcLqOav2A6IwTMxE4fPoSFZuWT8v5IioZfQCW8JKWdgKsyZCnFtwVrgUR+kSaplTGPM//thldF/rYHPR6+ygdjwycs3dt3i/G1k4t+CTR+vFkmFWIknDttqWNQpNpSGKrCvQ2ayIRslxGNAj2vqjFc+/4rnXZObubtFV2TiI10/PeJkHTtCYWYCKLyrSSSWtukNiJyjhNWtQ8iokGhGtHgjU9vPsqzPQ8tKT8YTgSoE58YYR1a2YmfarjHmaY5/lXW9B1gY8t3zNQXsrA8oHzv9uQO+6MZL3k+dNMZ0isht3k/yT7XCZCwoxTb8ldmXlrvGZN+zGp/n9oaXdcRz2R4LPjKVsvaqZZV4CgPREvIaF5HqObORFrejNgAU03tK+yoty6A4yN4doRcEoq1noKQ3hPPFITuvdxKGOe73dZ0HmeD5ZOoMclu2bQoh0f5192RlI9XQU0jfWPMs/fvWxaQb3e6uynt7gmUIgURjFAVfjcT6bN4doN7f4YzJxSBSF7o6bc+jsC/z3ZegQjqgemyhw+ISXz9tqphVElIexjvByuAROl7yxsTclcaaEg4OSwjVhoytZuoA3zfH+dRe08t5OyG2uPWLzl07yfjVk6pWB7MnViphHhFnJ2mY/DzrQTX0yU+/jEBU2jQsY1MZpry63z9ZArsS/szDBTbUaesuvHesjXi5b+1okEJLT6uBaiMk7EfJyGVgl7i0omTEJTOiOGknKlD0JRtqhxJBP9JFw7Im2lRAy0Y17gX5vT7hn0We64E5ZOyUr+sqkQYV+qtmScBoZIWPYXktSQ+0kEMUEvuRIra7Ts0Azs3jy8L62UrBpPXoAngjmlcp5GdQGZoME44cto+u5rCJ/5Uy3tmPh4vXWJF8zaYrNUVSTcc+xwgJbCt3QKRZxVWg8UmMK+VO21HMPMFHGS0WgorWoaRsCEYMcY/HxNRf4LesmWFEXTdxzk/9q8fUCrlmdkylBTXvgZIO5Nth4HEt3MCeGdIcB0yHrpHUiPS7mWmAHuE0lgS2taCohxY9iGzI0mS94rCVDJIIkIKGGTOu8yH80mS66ml7RYIVInBPucGc2SSb9ZEwCgP75iorBxaTm+3QRW+lyYxZCG/AdSaXkvupkTh0/RQaDDaLOcwqf6YfRLgCKx0+2/X4snJkAvpcrbvYE+8GRkErMpXLt90oDWRJXBYeYJQQ8QKpdOKdBUxTZaqBKqCskTrl2a2g7BSKmqslqorCSVBU0iDh9GkggiNk7j5nAGiMxhG0rUGpVGfZM2DW2yddciRiZWN9qIoakQpABpSn5r0IcxaXvAdkvZ7XqrAgCl1Z6ZRDT84M+ZeateThA/QEXY51o6twGC+8bL6EEEYun+mGw9gCiMU1Zau6YqiaSKw8c4EYf9rgROaeM0eWHDj0lVnu5J9tg7BN5L5nxN2ZoN+jBmaBrrHcjR8nIWE6VVTcPAIcqs6+A6HgpBStjZWZraDqh9ZKUkCC0DrH8B46Nk6xGxcTL5tEUUKyJxkcTJhjj8d2XSWvg58dxU7RmiEv0LQmjbF2O6z1jSOwxgLXXLACLWfawT1FmhqtyCRcKCf1UiDd+VQCJ1x3s4Vo0nhQj3JVuPiI1Thshq1tRQUfvsm0PEUPi3JALp/nYZDZOqPWMlhpMJw7W0J+ZPWgYULNRZLYNUgLSVV8jgVt3LRDD48hCfP19bkb9Nb/n/RRVhlzq7RRYUDr/8l8rUTCt4Opoy7/EkYuO0cAZ1aynjLVJ8GSueMCjsd2Vt+1KJg5nKqhvvUpnf0W6YwKrA7J6SGgaHPEKbcUpT2nQ1ThMXNI0KttcEAODEpUwCAFD4fbgukQWofXzPnYiZ+IFkqhCdKzlR2A1QVfDhU06BOXxNHlZT48fKTGXVnqtLF3k2MvjPmpxb9p8K/GP5tMI39VTPIHWguehkIn+4djnKnn56FtkLFXTLzFtrKwof0UvuD+RVQghSCsK166JsQPTtmRMAtPa3PgrwlmTJj86VHNgVrg1pSXF0CFA2r20giPLDNiSR1Gj/mx72nFha7bmttKrxIwaeAChUqYEQ8JdeyTJNH+0MUhUV0t5wbQb5viZzeosuGVAmLmgaFSroFgjhIKEXe3EsMYetYbfPPJBVSYSvh5birBpPCrGYkyz5YWMYgsK8GUTh8kcdFsYJkk/joExcUDKpuKS02nMhMQaA+EgGFUPB0QCiex1R1V2K2XLpozf301xB0+DQQGL/5yAc0Vub/t4tJCT1xwD+HW/5QlJXBvs80bMmAFBMkqaceXvMR3uH78pJ2owjnrQMyK/N2eP5FYjCVimIN9Eu64XNzgtoy1ze5xFK2Fo3AKBI0ud6q7IfBv8ZwF+ZcBuDrgMChimqzrhVJbpi5c25Gu65wSEHq2Hv+4+6NoJZQ323CCmr8sxF6GKClfGWFw6FpWItPsi7zcd+XVkZvnJuX2DVePISQVOZ+ngT5bKeBuNENGziwuY+kzo+Wphxcbg2BO7sk29SzB0C4voVFYUpk9LEILEQ8ZfhnKKP8H6Jo7yfXxpPuZMWNTlASIm9pv2owvyzcG3aRT6azIMS9iKaEEgkpZp5lDMnaMo4TqSEvZl9mQnVbYMIFLZ0MTO939fepIh5swqTvKyi4JAuGGkQFk0vJie3v3HETVUNY+IllFntLbC2Ml5ytMLTcYzE/rDLetvSRkJLjbe+RM20go+IOeFVmKMyTjXTCj4COHw+OeKws4q+jATvz7RkVADYpb828YMYz/t90pgVFXlG1vHDHNO3/nqFRFjv3JPa3iIJ4rJ4yCyt9sxE6OW8D5Ixa/KT6Qog/KLelswxzKC3EqBSghH/TLjEaE8kUNj6LcQ0qmxhc/T7HSmPqsn4MtFqnRWJE9wO0F01FdYrV96Sry3Y2uCQhlZBEVDDjvUfdb2HXP83Ma+UTF7SmBsyTREAIhGylpOeKGS+VMt+0xfpxW1DGwoOuWVwVajvJFpm9AWxmFeHbUIgJnV81DJSmAlzm/IAnBW+Jbe3dhdoKkiYLAjcSUxVkiljRG15wV+TrY9BaiFYeSfcvpOAHz9tf+3Emx72nBiLLNXPvaQp4tXLpuU7Y+k/GngmBhLx2HDt2kUetmaetrqvLeFrIctvdRO4M5EyozZO3VLaKmIOW9sEpM66foGnz6WPD4dkVu4AKHzpEKZ/rZpNCb2pWiHmLjA/DCxRWdoAACAASURBVIWOr6komJESlVcNUg4T+Z9iCv/APbfpYUr3ddwTrZzJSxpzmYM7QQAAAyuj7TsWuintbkL40iEfZl0IFeKQzNa/cAZ1A9iQSJlRG6dHp/bbA+CN8C1pYIaE26KVk4pMXLj3SIArtLRVWSTFDTMkzA1gPAXmmxQ1bVhtReG0mhnWPh8waKAfNA9bGVLYpb0C/zc4q3n5FdE6Rqg+rgw5awIASKuj6TcWeDqOIYjJWtr+u99l7d0d1mf11ilZMCihXojRBeHuh8TfgfBOD8w8c0J126KV5dlhM0v0BUiISmiqz8S7Wwfmvay3PgfTUyyM9jJ4D5h2g7CbCDuYxdtDGvLqDsVlBwN9Eex9DBByuH2X85oWi3U54/8KwBFJ/5OXNOYqPp4Qqvse9/EEJngN0CVl/FmCGjbFV4NpKL7IHPvcoxXhU7v1YRJa3Twm45Sh5D/XITzfgajXCHIQ9TOh6/cApsYiLxUoq244gZlvhJbM+aDHkpEklSUxOlA0zMAgLphV31NdIushCf5eM/BnqU04p+lhubWq8ZJIwhB63WsCQKDEJngF4J1hLmLwz7W0XZ/zc6hIr9Fbp2TCRJ8TJ64SSPQOEehZhySgWktbZkycsLDx5FjkpQIMaEuWytwhmdKTlpfKwCCe0ELsE/BpKpXiaHkER3o/fWDc0+Hz0O0nZPl1AMxoFmaq1NpXPGCA/CJ9DoHDPiM7RC5cub9cW1uR36dCRiJFVZDQ5f+YjBMAdKpUBebGsA2JzJJQV5XWtITN6puqlFU13g6QVnfZvxkOBgaHEpZu73wFUljnHgt3YsKuih8P2fXFci39llY13BiyJAYAIsxbOqUgbAXaeNI1K/MPJvbKWtrW5VyHVmngn/TWKdlYLEjoPYjZOD0+w7qPiBZpa00jqNv/1LinWUPgampRuqjxYhBr+gESc5ciSYZLtsEhBT2MPRL7lmhpe5T3M1y3+/bry6p23x6239BZx8GM5ppy6x8iUDNmumdaxglWf6slrqmLsrE6b+L7NRUF/9Jfs+TS3s0JjX2M2TgBQHdHwV/AvF1LWwbOyd3jmR8PuYmirLrhBGJ+lDXv0Ym5K6fmb9VVKQODJGD2+u7xwxx+pQTAyPbXcXnD/fdPqmq8JFSbnhx6dGbITiixqYq8s8ynqmR+VGvp+dcLpqlN0uDpeuuVCjw+vSChNariYpwevZ3aISjsG9J+mGjapEWNN8dDtt5MXdScrzKeY/Tm4vo9vhbm/EN+im9weEKL0WRSum8PF5S7n/OaF4szWv/+5KQqz0nBjrOqVIY6lxnNteXWhL3I8kwM9FLGSxL8aVra7zIfhzdzp/ytdnrBGr11SwmImFjrnY+duBgnAKidZl0FqK9qba+q6vzSas8t8ZKvB5OXNA71qv7Xieh4recI5tuWTqEOPfUyMEgm5oW+FX6yaErRQ2Bcu/tXWY7m2rpJ1Z7vZVnobdbEjGZWRdBjesDTccw+YV1n4e7ePY/3twfhmf6/b2k3596pt26HK3EzTgAgmTJLibFDU+Mej7eHSqs8yyLx6kkUE6s8xaqf14KoSOs5xFS1rKLwH3rqZWCQbAjgDLRe46O0Ji3tTfBifMPdeVfv+ZVz6vztN+3/vNdZkyrOXD4j/8M4qBsW3wzTWR1S3gcZ3DZc6zmv55erm7LPuT6QjMBAB+JqnJZOyfqOiH/ek0BUI4TSnD2Nb9ywuHVAPHWJhdKqphsE8ZsMHKn1HGK82TIgP6VnggYG8YLmYavF3/EzFZJf6zlyyyOmm3eVLr9t3gfzS6sabgw5awJmJcowdd2SPc0vLG+a0akhqL6HD7MuwAvWO+6qnVaQ8AD7w4m4GicAWFZeuAEsJgHQnoWAYLeo3vrShY2aqsrqxbg5nFFW5fkrQV3JoAztZ/KXnG66JhkBtwYGycK80O8W7LuZtfkOAABO6HRh5s5rZ5jYG9TrL1H7THwbsppmH/GIUH3VEhTNz8GdlhPw+MAHHq2pGPiAnvoZ6GCcAKC2ouBJMCJ1CjiaiF2l1Z5nJy9sCFvUK55UVrIoq/aU5loaP2fCbUxanEh7IKBZMF1VW5aryYPJwOBQwjLfV6uQSVNw7n52WY6DItKCOx0QdM0EweMgeWYfeds+pXBXltr4S+0jHWiVrKgduGjjzkEjyvTT0GA/uhgnAKgtL6gE47lIzgkYhSsUwoel1Z6HJy9p17Q5GQul1Y2XftO/4X0GljFhSCTnEuAnpl8uq7Bu0ks/A4NUJyOvbZYX6au1tn8nL/SzXZBYGQeVgtI2q/DaxqFHfNtP9TyQwa2al/EAwA8LHhkwf/c36SMvWTWewldjMIiZ2BK/9gYRex/gGy0ZjYNBGB3huWYAkxVf57VlVQ2PqgLPtxZa34nXslnZvLaBMHl/BlKvY7DM0dloFYw7jDLmBoc7VAmVZ7Vc0Ya8d9PQeVxvbT2mwfgyM/jqfZbSpJ7a+sIv0xZuaayafszH8dCNZ+GILWlF07KV5hst/m+GWKJ4gqiQ8ExhZfsnmeddcqgkr+4L6Gec0BP/NHkJn636GlcwYVzEHRD1Y2AaMabl7mnwlFU3vAbQPy0oeHlRObVF0tXERfuOF+y/gqFcDHSP6QmojWBO/z24HSwm1VQUPBllBwYGhxQ0D808vfm0FlP/FzJ535mh2r2TNylkH2c214qLG+dMvKRxzsTrf3PFvh1ppzjfy76gKn3fmDcjyaTfdkvWyd9ZTpqVqTRf1O3/ZtDQ7uhzIHeKHDzR/75v/p1z+fnLy/M+i7ojg4jR1TgBQCDm5+qyas+nDNyNKJcSmYQVwHUArvOyp6u0uuFzgL4C6EuAPQy0CVAbM5lA3A+MfgR1CDOOI6LjmH3De6LHRExRZMTYQYSfL6soSGjhLQODVIcWYh9j79ltt1jnWdT2GUQ/HGn1OcELY2coLTi7eRkAoJ/SgKL2f+UUtf/r0oua5l66x/wj/89+fUFzq1SwU4XpOwXmZpakFou/U5XQlSNYye2nNg3MUFoG5ygNBRZlT9qw7tid/faah+NvA+at2Z5VfGnNtDxNbvMG8UN347SfmnLrH0oXeT6FqtaCRETrvQfDROkATun56xkABIDBwP4BQT2Bcj3/xgcC6oU5/edGQlcDg+AQwJjrmdk5K+t9gJZJ8P33GbOu3zh0SrlBzzu7eRky1B9mx7FwJwZ7N5kGe1EIoBDAKL10P5AvMkrw9wEPLElrOXXa4tuN+mfJQDeHiGDUTrOuImE+C8wJLxoWM4y/ZSgFZxuGycAgPBnz2lea1C5HN2X+N1noqv7BK7gfOGtKBepyrlcWH1F78323FN1sFOZMHgk1TgBQMy1vo0LpxQC/kGjZUcFoYeKZtRXWCQtnUHey1TEw6CuYF/jXZlPTyFZR+O7beaUhZ02/3D0r6Kwp0bSLPKwq/MN3jw188MxFM47WlH3dQD8Stqx3IAGPlysmLmy6jITyEEDHJEOP3iAGM/A0qbi9tqIwoUW2DAwOFWgOdkxe8vH58Hp3Asg6+PiIjjUY1f5aEjT7HwyBDdlX+N4omPrQp4NtvzdcxVODpBin/Syfnv/iuDn8Rm6aZzYDFQANTKY++yGwi4F7aysK30q2LgYGfR3Fz/NImH9gmADgrObkVTZnEDZnlKh1ub94ZV3u5RVGmZvUIqnGCQBWzaZOAH+avITnKv7GKcSYFWkwbDwgBjOpr4FN99cc4uWWDQwSRWlVw42higmmK/uSMmtiCHySdbZ/ffbPX9jY7/JbayvytwE3hT/RIKFEG+ijG+OeZqnf7uaLBanXM/hiEGXqKpD5PyDxJJPp0eXTcr7QVZaBwWHE5CWNuYqPtxIFr4Umsf+ee78e+59OkTGrv3/bSBN7dd0D323+ET7LdGz/OPO8mq/6nVO12HAPT2lSzjgdyIS5TXkmi3IZmM5kYntc9qaYu4loA4NcYHq9tjzPjWABGQYGBjFRWtVwIxGtDHaMmbdKZnHK0ikFLQDAt6DgP+aiKSpJV+X7vj0hR90b80upj9KxPe1k33eWEf/5Om3U6+v73Th/6Yy8LbH2a5AYUto4HcyExU3DJVZPh8rHA3QsEY5jsJWYshjIJkIWmP0AtzOoDUxtEOoOYukrJvVLMD6TzNZ6oxiggYH+lFV73kdPPOIPIBJnLpuW7wx1btctacd+keEYx8DoNH/7sVnccqSJO7MsapfJzF3Cwl2kkgQvZbKX0tVukam0mgZ07hP997aZrVuapUEffJR9wT/vnXXGWuPls2/Sp4yTgYFB36C0qmkYkbo16EHGvJoKq1H7zKBXEh7nZGBgcBhAamWwj5l5qzBT0GMGBgdizJwMDAziysQFTaOEpH4Q7Fi45TwDg/0YMycDA4O4IoQyL+gBxjzDMBloxTBOBgYGcWPSoiYHiM48+HNmNBvLeQaRkPQgXAMDgx9Adru90O/3W7777jvP1q1bu5KtkFZUVicE3SsgVO53G091bDbbmQA66+rq1idbl8OZhBgnh8OxgplHEFEHM3cS/bCiLTOrAL5l5v8A+A8zf1ZXV/dlIvQzMEgmNpstXwhxGYArAfyUiPoB8FgsFv+wYcOsQ4cOTSOibczsZObVO3bseCkVDVZpVdMwgjrh4M+Z0SyZg8c7pSJCiDIA3wEwjFMSSYhxYuaBRLRGVdXXAv8PpcsQAEcT0WlEdKYsyxsURfnNmjVrNiVCz1ShuLj4x2az+Rq/379o7dq1e5Ktj4E+BIzSvQCuIKKXFUVZ7PP51q5fv37fQU3JbrefAMBBRDcMHTp0/pAhQ+a1tLQs+uijj9qToHpwSJkXzMeKgJV9ZdYUoC3wpzvGWA9Nopb1ulRV/dTtdmtOpFpcXJxhNpunmUymt2RZrnG5XL/VU8FUwmKxzAYwyWw27wGwKNn6GMQfu91+DRH9hYhqt23bdkyYmRC73e5PAXwKYHFJScnxkiTdnZ+fv1GW5StcLlfSy4eXVXt+D+Dygz9nRjMggjtIpC7+wJ/uGGM9NAlxiCCiiG90fX19p8vleqirq2sUEZU5HI5L9dAtFWHmucz8R5/P90yydTGIP7IszySiX3m9XofT6bwn0iW6NWvWfOFyuX7BzPcBcNrt9gt0UlUzDA6RCQLzehKr9imUwJ/uGGM9NAmJc3I4HE+rqvovt9u9Msrz/4+ZV3Z3d49cv3797jirZ2CQMOx2++1ENM7n811YX1/fGGt/DofjLADP+Xy+s9auXRs0tsggMmRZng/gO5fLdX+ydTmc6ROu5E6n8xUAG81m80XJ1sXAIFocDkcxEd3c3t5+XjwMEwA4nc53VFX9g9lsfmn06NHWePRpYJAK9AnjBADM/L4QYmSy9TAwiIaRI0dmMfMjACZt3Lgxrs4Bbrd7HoDNGRkZD8SzXwODZNJnjBOAjwGcnGwlDAyiIT8/fyYRrXa5XG/r0b+iKHcz8wSHw1GsR/8GBommzxgnItpDRIOSrYeBQaQUFRWZAUz1+/0P6SWjrq6ujpmvdDqdG/SSYWCQSPqMcWLmEQC+TrYeBqEpLi7OOOmkk7KTrUeqkZGR8XNm/nTNmjW6Vlp2u93PI0Eu0AYGetNn0hcR0QnM/FW4drIsX0dErU6n85/RypJl+WxmPsbtdi/Teo7D4biUmS8BcBwRHQcgnZm/Q0+2i5cAvOB2u/dq6ctmsw0VQkxqb2+/Z+PGjb4wul5HRDucTqf7IH1OZ+ZfAhhBRD9i5lwAXxLRpwA+6erqWhkk2DMiZFk+mpl/QUSXADgBgFRYWNjqcDg6mfljZv6YiN6Kdikrntc0Ef2GQgjxcwCPxKu/eFFSUtJPkqTLAFwG4McABqHHg/c7AJ8B+Edzc/NLsQT6nnLKKXm5ubnjAZzJzIOJaAAz7wKwBT3X+w232/1urN+luLj4WJPJdIkQYjQzDwSQB2A3gB1EtEVRlCfr6uq2xyIjMKZuRM/v5hhmzkGMY6qvjPXRo0dbMzIyrmLmy9HzW7ESUWfgmfy5qqpv1dXVPQngexkWHA7HFczc7nK5Xo9UZp+ZOQH4CYD6cI2I6EJVVW0xyvopEV2lpaHdbh8ty/IaZp5JRG/6/f7ZXV1dJ3m93qF+v/8KIqoVQshEtEmW5T8WFRWFLT9NRHlE9KtwP9ZA2wuZuWT//2022xhZllcz8x8AbGXmOV6v98z29vbhzDwjkAJnZFpa2ieyLF+m5TsGQ5bliQDWAchm5gdUVT3N5XL1czqdg1RVHQ1gXmApdpHD4VgWyYxKj2uqZ78asKmqWhenvuKCw+GwS5L0IRFdCOApAJf7fL7h27dvH4qeYNqnAVyWn5//uSzLNyLCsJOioiKzw+H4a25u7mYAZzDzM8w8y+v1nkNEtwN4nZkFEf1DluWVY8aMGRjN9yguLi5wOBxPWyyWV4hoMIAnFEW5E8A1AP7IzK8zc4EQol6W5RccDsfpkcoIjClXYEx9HRhTjniMqb4w1m0227np6envoucZ/GB7e/tol8uV53Q6j+zu7r4KwItCiAsdDscGWZbPP+j0SwGMjkZun5g5ORwOOzMPcrlcYQPVmLldCBFTShdm7iCisH2UlJQcL4R4FsAvnU7nO0GabAn8/XPs2LEDTCbTwqysLPfpp59+8YYNG3aF6tfv93eYzWZNpeSZuR2BtxWbzXaJJEn3MfOdLpfrX0Gavxf4ezxwTWsdDscZTqfz11pkBWTkS5K0hJmP8vl8JfX19T+YzQZmHW8DeLuoqGhZVlbWA4WFhR/Y7fbrwr0l63VN9eo3HCUlJccTkS/Wt/Y4ImRZ/jUzTySi651O5w9e+LZu3fo1epbQn7Pb7SVCiKccDse5TqfzJmhYNhw7duwws9n8JICtfr//R2vWrGk9qMlOABsAYMyYMfMtFsvv09PTP7TZbCfU1dU1af0iNpvtXEmSapi5xuVyXYsfBs5uDvz7bFFR0d2ZmZlXA3jB4XDMdDqdq7TIkGX5MiL6k15jKpXHOgDJbrf/TghxJTNf4nQ6D85EwoG40xcBvGiz2c6UJOkJWZYfcrlcD+5vRESavt/BpPzM6aSTTrIAWEpElQBUDafEI/WIL1wfw4cPTzeZTM+oqjorxMPue6xdu3aPy+W6moheSEtL6/UtkYjCyj8APzN77Xb7BUKIqdu2bTs9xI/1ezidTnd7e/tYAJNtNtsojbIkIcRqVVU3u1wuezDDdDAbN27scLlc5cx8hxDi6WOPPTYtVFu9rqme9yocRHQqM/87lj7iicPheIqIxvh8vtOCGaaDcbvda1RV/SkzD3Q4HCvCtS8qKso0mUxuVVWfdjqd1wYxTN9j/fr1+9xu963M/KYQolLr95Bl+U5JkhYrinK1y+X6I8JkdNi4caPP7XY/5vf7iwHc43A4ZoeTEci8MUXPMZXCYx2yLD8lhDi6qanpDC0psurq6lZ3dXWdAuBCm8127f7PVVUNOysMRkobJ7vd3t9qtf5NVdVFWt90AKiBDOdRQ0QqEfXax+DBg89g5n1ut/vZSPp2Op331NXVfdhbG5PJFFb+AahCiG4i+h0zl0WSCmfjxo0NzHy/EKIaGpZt7Hb7TQA63W733dD2ovBfXC7Xc8y88YgjjpgRqo1e11TPexUOIiokopRI6OlwOM5j5hFOp/NnkQQBu93uvS6X6/+YeZTD4bD31nbjxo0dzFzkdrvnRqjerwDcJMvyceEaBmajs7xe75hIy1qsXbt2m6IoF6uq2useDDObiehuvcdUqo51h8NxHoAjnU7nLyPZc1y/fv3ub7/99mJJku4pKSk5CT2GN2im73CkpHGy2Wz5drt9qhDidWZ+xu12L0y2TgcjSdJoACnxRszM44lontvt/i7Scz0ezwIiOlaW5R/31m7kyJFZQojfA5iKCA3TfhRF+bUQ4o7i4uKCYMf1uqbJvFdEZGXmuGSDiBHBzA+ixwhEc/8UVVV/zcwPIczDLRpnEpfLtYOIXj1wTyUUkiTNVVX1T9Fm2airq/uP2+2u6a0NEU0govl6jqloSMRYx/9+K3dFo+NXX33Vzcx/NJlMtzJzVEt6QAL3nIhoksPhODvUcWYWAIYCOB5ACzPf4nQ6ixDlgzABHMvMnyZbiQCnO53OiGYF+9m0aZPX4XB8zMzHo8dDKyh5eXm3MfMLLpfr/WiVXLNmzRcOh+Mls9k8EcCDQZrodU2Tea+sRLQjSbL/i81muxFAk5ZloFDU1dW95HA47rTZbNfU1dU9EUf1AACqqn4N4Oje2siyfBERHe1yuR6Ot/yDGKT3mIoS3cd64Ley0+VyuaJV0uVyPepwOCoARL3ykEiHiLUAenMnJGbux8w5RDSYiMY7HI7rVVXdTESPuVyuzb2cm3BUVf2MiH6SbD0CfIgYjDgzf0VEx/fWhoiuBTA9WhkHyFqHEN47el3TZN4rImJmTkiC5d4QQlQQ0W2x9qMoyt1CiDkA4m6cAGwVQowN0+Z3zPwb6B/PpfuYihLd9RJCVDBzyOV3jaiB2ddSAFElJE6YcWLmTS6X641IzikqKsrMysqaSkRv2O32JW63+wGkTpChk4jutNlsQ1PAEyvq2UyALeiJUwqFxMxH+3y+jTHKgaqqW4QQ14Y4rNc1Tdq9YuZGZg66jJlAiIiO7+rqivn+KYqyXgjxY/RsCcR1VYOZdwAYHOp4SUlJPyI6raura0085YZA7zEVLXrrRUQ0orm5OR4Z7t8johwOXlw2LCm557SfgKfXQ21tbScS0VEOh8MdSAWTdNxu93vMXCVJ0suBjb9kEuuyUSMRhYzpsdlswwDsjFMm7f8Q0THBDuh1TZN5r4ioUQiRn0iZBzNmzJijmLk91kBMoKfOGoAGWZaHxUG170FEPmaWQh2XJKkYQFuCyuboOqZiQFe9Ar+V1nhUWHa5XF8jhslEn4hz2rhxYweAWbIsuzIzM28DcF+ydQIAl8v1J7vd3iZJ0juyLL/NzCs6OjrcAX0PGQJZFN6Px4tBZ2fnrqysrIHDhw9PD+ZtpNc1Tda9UlW1kYiSWsoiLS1tBP4X8xMPNquqejwiTCc2duzYAUT0IyGEFUAGEWUG9pr9ADoBjOjtfFVVjxJCfBm11gZhsVgsxwMIGyKiET+ArdGe3CeMUwC/qqq/EELUjx079um1a9duSbZC6CmfPa+oqGhFVlZWhRCiMisra5QsyxsCcRtvBhJxpspSZLQcB+DcrKyseP1ovxs4cGBuCFdYva5psu7VRwDuiXOfEcHMI4goXvcOADYLIY4H8GpvjcaOHTvMZDJdA+AcAD8hot3MvI2I9jBzJzN3BdyoTQAy0JMWJyQBt3xd8xMaIK6/FWaO+qWoLxkn1NXV/UeW5TpJki4CkDLu5YH6PH8C8KdTTjklr1+/fucQ0bkAVsiyfASA1URUE0u+v2RCRLlE9LjT6ZyWKJl6XdNE3yu32/2JLMvW008/fVAsmSZiQQiRw8y9BsNGAhE1MnNhqOOBDBtziehsZn5ZVdU5nZ2db4VL0WO32y8got/00iSdmZujVtxAC9mxuH8fDBG1R7vn1KeMEwAQ0SYAJyZbj1B88MEHzQCeDfyhpKTkSEmS/o+Z/yLL8m+I6PaDEzf2ARqYOWQYgN7odU0TdK9UAOsyMzOLAfwjxr6iU0BVvySiM+PY5dHM/FqwAzabbZQQ4hUiWul0OgcjTOaGSBBCeLTEQRnExGYiittYZ+ZjADijOTelHSKCwcyfQB8vGF1Ys2bNty6Xq9blcv0EwFxmjir5ZDIJJHDVwy02KvS6pnr1y8yvABgfaz/RQkRfBPYN48VxRPSDvZ+ioqJcIcRzAOYHcrjFzTAF2JtKv8NDEVVVNwcMSryIuq8+Z5yIqJWIsnppwohxRkhE6bGcHwLV5XI9BeBmZn62uLg4QwcZuhDIDXdUCtZq0uuaxrXfjo6OFcx8gd1uPyJO+gUl4LDyA283j8ezBT0u2vFaKTm2q6vrB3s/mZmZNwH40OVy/SVOcr6H1+t9n5mHDh8+XI/xaQBg586dW4hoKIL8jiLFbrf3J6KcaM/vc8aJmUeil6AuIvo2cHFjQbeATZfL9TQR7RNCaE7AmGxcLtcOAFsKCwtTcsaq1zWNV7+Bfa4nANwcH82Ck5WVdYcsy/cf/PmmTZu8AL6x2Ww/ilWG3W7vz8zKu+++6zn4GBH9nJl1KUMPAPX19V8R0bdDhgzp1avPIHoCTkq7xo4dOzzWvoQQxyIGB6M+Z5yIaJSqqu+FOq6q6hfMfGwsMpj51FjO19D/h5Ik9RnjBADMvJKZZyVbj1DodU3j1a/X632AiKYWFxfHPd8aAAQMzxRmnhPsODP/SwgxOVY5QogbAKwOcfhoAFGnvAmzIgIAYObHiShhjjmHI8z8ptlsLo1DPxOY+a1oz+9TximwrCQDCBnp7vf7v0AM65yBJZyY3zA10JkAGXFj+/btDwI4w2azjUm2Lr2g1zWNud9169ZtBfAri8XyKOLviGQSQvydmWeHSgja3t5+LxH9QpblIdEKKSoqygVwh8/nC+pRR0Sq3+//wYxKIwJA2Aeioih/IqJLUiDw/ZClu7u7EsDkaAtAAj2ViYnoVMSQW7BPGSer1ToPQH1vBeu8Xu8WIsqSZVmORobFYvkLM/danl2W5coYB8fpPp8v5tLUiSQw3b89kFctak455ZS8YJ/rdU1T6V65XK5aZt4WqIsUFwN10kknWWRZfgrAB263O2QxzkDJhLkAKqOVlZmZeQeA5+rr6z8PdpyZ37NYLFGtOtjt9ilE9EK4dmvWrGlVVfW3kiTF9DuMY5XjQ47169d/w8w1aWlpv422D4vFcg+AZeiJX4uKPmOc7Hb7VUR0TktLy6Te2m3cuNGnquqvAMxFhN/PZrNdyMwDAx6BvbFdkqRXonkLlWX5ZCLqV19fHzKYUFVVzYlCqSezaKyJRTWd73K5ngPQZbfb79Z6zoGUlJQcmZOTKbYgxwAAIABJREFU867dbj8nyGG9rqmu9ypSPB7PdQDSZFl+IdYHZFFRUabVan2RiDwul2tquPbbt2+fD+BMm812SaSyHA7H6UKIiT6fr7KXZu8CiLgcuCzLY4UQss/ne4uIwv6u3G73IwDy7HZ7RaSyAOCMM84Ynp2d/WFxcfFRwY4nckyl6ljft2/f/QCucjgcZ0UqwOFwXMrMBU6nczmAqLPKJMQ49ZYvKxx2u/0Ih8OxnIgWqqp6dSA2pVfcbnctAL/dbv89NH5HWZbHS5I0s729vVwIYUEvb7Yul2s5ET1IRK9EMvUtKioqRE9MzXXopQCXEELqTf6BMLNERLF61pi0yuvs7LxeCHGlLMuvjB07doBWASUlJaeZTKa3iehht9v9g3Vova6p3vcqUjZt2uR1Op3XANicnZ39od1uvyqafmw227nZ2dkbmXmT0+mcokXHrVu3dimKcrUkSSvsdvufoNEjS5blmcz8rKIoN6xduzZk4USPxzOfmUsOrIKq4XtcCOB+n883k4jyoe13yF6v92oimi7L8lOB5UZN2O32c9LS0t5h5lvr6+t3Bu08gWMqVcf6Bx980MzMNzHzC7Is3wVtRk1yOBx/ZuY/tbe3Xw3Ar+VlozdFE4Fm61lUVFSYlZU1Aj0pc04homuZ+WGPxzNi06ZNbRq7UQFcQ0QrZFmuA1Aaqsyw3W4fSURzAKgNDQ1Xbtq0qU2WZYmZLb0JcDqdC+x2u0hLS/vI4XA8oqrqA6GKrI0cOTIrNzf3pkAq+ofClQpXFMUiSVKv8vdDRBYAmtqGIvBdNfWxYcOGXWPGjHGkp6cvMZvNHzocjhk7d+588auvvuoO1t7hcBQz890AMhVFubG3yqV6XVM971WUqC6Xa5bNZntCCPGQLMu3Aniku7v75fXr138T6qTi4uIMk8l0vhBiAnrGx2S32x1RkPCaNWv+XVJScqYkSX93OBxjfT7f9LVr1wZdKRg7duwxJpPpAQA5nZ2do8NluAiMnaskSXrD4XAUd3V1/TXU9ykpKTlNkqTbAWR7PJ6LNm3a1Gaz2UYwc5qW77Fu3bqtRUVFJVlZWY9kZ2d/4HA4pjmdzjcQwjtMluXzAfwWQJPf779kzZo1m0L1ncgxlcpj3e12v2az2S6SJOkxWZaLfT7frfX19UFTG40dO/YnJpOpipn9qqpeEvBQjYlEGadcIcTDDodDS8qhhkA+ps0Avuzq6hoVTRbiQEbcs+x2exkRvSnLsh89m3OfEVEWM/+EiE4EsCHwsDo44j3o3siBBHK1PZaVlXUbEW2SZXkXgK1EtJWZuwEMQU98ydEAVnm93nNCva0dCBHlEVHGSSedZAm4AfdGHmLfsM+Dhu+7n0B262vtdnsJEd1+5JFHVh155JEbAewgIg8zH4WeQM2hzPwNM9/rdrtf1tK3XtdUr35jIWCobYHy6Zenp6f/yuFwtAH4mpn3ANgDIB3AAABHENHJzOxi5lXt7e2rwqUDCkXgwXyqw+GYYjabH5NlOYOINjLztwCYiAYx8ygiymDmJS6Xaw40lsdwuVyflZSUnCBJ0oz09PQNsizvIKJtzLwNQBqAo4noGGb+DsCDLpfrFXx/1qd5FrRx48YGABfbbLYLhRCzHA7HCmZeT0Q7mbkFwJBABvzBzPwFEd3pdDrrNXSdsDGV6mO9rq6urri4+ASz2XyrxWJ5RZblTiL6EMB3qqpKRDQIwGlE1AHg/9s79zg5yirv/85T3T1XMjFGkIQkEw0XGQgjHTLp7qqnlItyib6CSlCR2y6sYkQ+uCzLRZeXi7sCIquusoCAqwgGg8t6yQqJaz3VM5NJCAnhRYIkYUIMBCQmGTKZS3c/5/1jetwhmZm+Vc90w/P9fPqP6X7q1Jl6TtWp53LOuc7zvBUl6vdXJqQIWjweP3Tv3r37a2trB9atW1d0TflSiEaj0xsbGz+gtT6GiPZnMpktQogtxZSUHoNQdl1jLoBmZhbM3J3JZLp7enpezsPwqpZs3a0F2azR0zCU1v95pdRWlJYloFzXtGL7KjtamUlEhzHzoQD6mXknM+/s6+t7vhxZ1LPb0I+1LGsGMxMz7ySiP44125Av0Wg0HIlE5kQikbkYSnk0QERbtdabiykznsf5murr6xdgyJE3EdHWTCbzQjKZ7EblVtSuKhzHORZDo/bDmbnXsqxN/f39L4xVjsV13fu11k/7vv+9idXUYDAYDIYxkFIudxzn/GKOrZrdegaDwWCoLoiohZmfLeZY45wMBoPBEDjz5s2rATBn9+7dRU0PG+dkMBgMhgMpOfHrjBkzjgWwpdg1XOOcDHBd9zTbtqOTrYdhaPOQbdufRxXWWjO8PVi0aFGzlPLp7MinFG4AsKzYg80NMA7z5s2rmTFjxkVEdAIzH0NEGWbewMwrR9l6XrUw81IhxNMYJ2ehYWIIhUIzATwI4KFJVsXwDmX16tXdUspNM2fOvH7z5s1fL0aGlPJcInrfvn37zitWj6p0TrFY7JhwOHxeOp3+/ngR66Xguu6HmfnfAazJZDK/Zub7MZRg84NEdJuU8tJ0On15uc4/wezLfsZlIq57MVSqXsWQSqXejEQi+2G2Plc8bye7OxBmXkpEnVLKzUqp/yjk2EQi0UJEdzLzGcXG4gFV6pwikchVAC4Nh8OvA/h+0PLb2tqOALCMiM4dJUPA6mg0el9DQ8Md4XB4OQAX1f8gSRFRTiMq93UvliL0slpbWw/ZsGHDXkxCzN14MHOamYu+oQ0TR6XeD0Hg+/6fbds+WQixUkoZA/CNbF23MWlra5tSW1t7I4CztdZf8n2/qF16w1Slc8pmV34tnU6PmYW5FGpqau5i5ruVUqOmrsm+DVwlpex0HOcK3/fvKoceEwURaa11Tgdb7uteLIXqFY/HPxAOh5+NRqNTg0izEiSRSCRDRNX+svOOoFLvh6BIJpMvt7S0nDh9+vTLAXS4rvuk1nq9EKJba71Naz0QCoWOYuajiehoZv4IMz+8Z8+e4zZu3Nhb6vknJENEteG67p5UKnVCR0fHtvHaSSnPAXCVUsqeINXKwjstijubHWKbUspChY2cpJSziGi953nTJ1sXg2GYaDRaX1dXt0QIcRQRzWHmOdlcf5uYeRMzbyKiNblGV4VQlSOnchKLxWYyc6Sjo+PlPJqvJ6JWDO16NG+7VcLAwMBgTU3NpKTRMhiqkWzarAcm8pxmK/kBZNP2v4k8Hlw9PT27mbmupaXFOPkqIp1OZzBG9mqDwVAZGOd0APv27XsJwHvyqRHT2Nj4fgA73s5JXd+OWJZlRkwGQ4VjnNMBbNy4sZeIVtXX138+V1siOgeAmgC1DAaD4R2FcU6jcycRXd3W1jZlrAbxeHwOES3NUbbaYHhHEovF6lpaWhonWw/DENXYH2VfK2ltbZ3a1NR0LoAPMfMRRHQoM+8EsAXAVmZ+0vf9NYXItG17thDi0t7e3ptKCfIaC8/zVkgpk7W1tf8G4KARVPb8TzLz9WNVhpwMFi5c+O66urpPMvMnABwD4N1E1MfMmwFs0lqvSiaTj6DIjQClXPdidXNd92xm7lVKPVGMXlLK6wG8B0A/htaZGEAdEYWllDePbJstgR1i5ila6x8kk8lnxvufymHb5cZ13Y8x82IMFYM8EkBttvDfVmb+FYDHi6lxJqWcy8znE9FiAB8AYE2fPv1N13X7mPlZZn6WiFYppX5XiFzHcS5i5udHVlCORqPhhoaGS4jIBnA8M08D8Gci2qi1vs/3/XbbttuEEI5S6o5C/5cDEFLKrwP42YH1rUp9DsVisXmhUGixEGIhMx+GoSKAr2GoaOeWTCbzSDKZzGdj1kGUqz+GKZcdjaRsI6doNBp2Xfe2pqamFwEsYuafM/OVg4ODpxDR1QCeYGZBRL+QUj7Y1tZ2WL6ys9Ujry2HYxqmp6fnS8yccBxn6cjvpZQftCzLY+bbKmnrtW3bp9bW1q4BcByAO3p7excqpaZ6njdjYGDgkwD+Swhxuuu6a7Mlqwum2Oteom4fA7CwWL2YeS8z78p+3gDwBhH9hZkZwBsHfph5F4A3hBBjriOW07bLheM4C6WU7cz8FSJamU6nr+rv728ZHBycnU6nzyaiHwohZLZK8C3RaLQ+X9lSyksArAbQyMy3a60XKKUO8TzvvVrrhQDuIqLXiej7ruveW8gbPBF9jIj+2v+O45zV2Ni4BkOFIpdprc9g5jZm/qLWeiuAwwFgYGBgGxHdLKWcm++5RsN13QSAy1OpVPcouhV1P8RisWmu6y6LRCIriOgIAA9nMplrAJwH4BZmfoKZpwkhOqWUj7uue1Ih8svZH+W0owMpS5xTPB6fEw6HHwHQnU6nL2tvb39zrLZtbW1TIpHIPwkhPpfJZD6QTCZ355Ifi8XmhcPhp5VSY067BYFt20cJIXwiWup53i8cx7mWiM4noi+MkjlisrAcx/m6EOIcZj43V/VS27Y/ZFnWwwBu9zzvTiD/OKcirntRujHzt4bfeF3XvR/A/xvWNQi9Fi5c+O7a2trtSqmCb5xy23Y54pwSicTRoVBoJYALctltPB4/NBQKfRfAvL6+vrPWrl27c6y2tm2/y7Ksf2fmmalU6sJcswjZism3E9FHtdafzWdU6bruj5l5tVLq36SUSwBcnk6nL+no6NiS61gp5YNEtNXzvJtytR3n/Pcw82tKqa8d+FsxzyHbtk+1LOs+Zr5PKfXPGKdSdDQaDdfX1y8hotuI6Cue5z2aQ3ZZ+6NcdjQWgY+cotFofSgU8rXWyzzP+8x4Ny8AdHV19fi+/1VmXimEuDGfc2RT7ZR9K3Aymfyj1vrjAO5xXXetEOLwXbt2RSvIMUFK+TMhxNzdu3cvyqesdjKZ/H1/f38rgDOklOcCADPnFaNV6HUvQbfTbdv+zPD3Wutx30wnyh4mwraDprm5uTYUCv1ca31lPnbb0dHxulJqCRE9XlNTM96IzxJC/F5r/aJSyslnenvdunX7lVJfYuZ/EEIsyzPrdZqZB6SUJxPR3yqlTs7HMQEAM38fwMUo8jk3f/78BgCfBnDPaL8XcT9cY1nWDzKZzBKl1C0YxzEBQ5lofN//STqdjgG4yXXdq8ZpXtb+KKMdjUngzmndunX7mTnq+/63Czz0WgAXSymPzNUwFArpiUjx0tzcXCuEOB/ATmaeDeDR5557LmeC1InCdd3TAMzwPO+CQtKFdHV1vbZjx47FAG5JJBJHE1FeW+ELue6l6PbKK6+cZVnWTYlEogX/u04UiF6lMBG2HTRHHHHEImbu8X1/eSHHeZ5303hrbo7jXAygz/f9r6HAAHSl1GPMvO7www+/IldbZtbMPEBE/7e/v/9i5Higj8T3/TXMvNtxnNMK0W+YqVOnnsfM/lhZDwqxu+x9duXg4GDbyPWzfOjo6NiWyWTO0lr3jNWm3P1RLjsaj7KsORWzEKaU2k5E/83MiXLoVCi2bZ8we/bsNQD6d+zY0aq1XgJgmeM4Betn2/a7EonEgoBVFMx8B4B/LObgzZs3DwC4NRQKfYWZB4JVrXTdmPmWUCj0VWbeH7BuJVFttm1Z1kIATwUpc/78+Q1CiH8C8EUUmRklk8lcJ4T4h1gsNi1XW8uyHK31j7q6uv5U6HmY+V4iuqwYHQFcRkT3FnnsW7As69ta61s7Ozv/UszxyWRyq+/7943220T0RznsKBcVtZVca/0ShhY6JxXXda+yLOshZv6iUurqzZs3DySTyZUALiCiXziOM+4C/YEIIc4JhUJ3B6mjbdsXAtihlCo6zkop9WNmPjG7Sy0wgtINwPEAqmr761hMom3PY+aXghQ4derUv2fmx5VS64uV0d7e/gKAX4XD4UtytWXmTw0ODhZVtG5wcPAhIjr5pJNOem8hx9m2fQIRzfA87zfFnHckUsoziWiu7/uBPgOGmaD+CNyOclFRzglAtxDifZOpgJTydmY+a/fu3W2+77eP/M3zvBVE9DdE9Esp5QcLEHskM28IUk8hxFJmvrVEMRrAt7PbuwMjKN2yo69PB6FTBTAptq21fp6IjgtSJhF9hogeL1UOM6/G0DbnXOfzurq6xpzSGo+urq4eZn6srq7uokKOE0JcprW+HwVMI47D15n5epRpXXQi+qMcdpSLinJOzLwdwBGTdX7Hcb4J4MRUKrV4rHUSz/N+SURfIKLfxOPxvDqLiKJEFGS8CxHRUXv37g3C4T1NRLMCkDNM0LqVdUfmRDGJtu0R0WLbtmcHJM9i5rmDg4MlV03WWm8B8P482nmlnCeTydwL4FLkuTs5u/35M8z8w1LOCwCJROIQIlowMDDQnrt1UUxUfwRtRzmpKOdERClmDnSKKV+klNcQUSyVSi3u7OzsG6+t53m/AHBFOBz+70QicXQO0YKZF6ZSqY6gdG1ra5vJzG8GUTNFKfUSAnyjq2TdJpPJsm3f959m5u9ZlvXr7AaTkrBtew6AHcWunRzAViLK6ZxQ4uilvb19NYBe27ZPyad9XV3dEgCriw2AHYllWTEA+7q6ul4rVdZoTFR/BG1H+TCh2bTj8fihRPQ+IcS7MRSlX8/MAkMPoD4AR02kPsO0tbUdRkTXMnMsl2MaxvO8Rx3HsSzLekJKeapS6sXR2rmuGwUw2NHR8Yeg9I1EIkcDCCozRRpAd0CyKlq3clKptg0ASqlbHcfZZ1nW/0gpf8fMD+zfv9/PlkEoiGw2gPXRaDRcql59fX07GxoaDmtubq7t7u7uL1XeeDDzPZZlXQZgZa62QohLmfm2IM6rtZ4phPhjELJGYyL7I0g7yoeyOqd4PD4nFAqdB+AUAMcR0WvMvI2IXmfmPmbuz27FDAGow1Bamwmntrb2egCP5hOLMxLf9x+RUgoAqxKJxGnZRcW3oLX+BBE9hmDrPR1FRIGlTWLmUR1rkVSyboFRLbadhX3fvysajT7Q0NCwVAhxY0NDwwlSyrXZGKyVnuetRX6j1CMBnNrQ0BBUH7962GGHNZXbOb355ps/aWpquiUejx/a0dHx+ljtpJTHA2j2ff9XQZyXiKYT0UHPhQCZyP4I0o5yUhbnlI0O/jYRnczMv9Za39nX17cqV5oPx3E+SkTXl0OncbAAXJpOp1uLOVgp9VMpJUKh0CrHcT7i+/5bRkhE9AkiujIQTf+XxiC3WBNR71A2n0CoZN1Kpsps+y1kS9LfCuDW1tbWqYcccsgpRHQqgAeklIcD+D0R3ed53i/HkkFETUT0kOd5l0+U3kGwYcOGPVLKx8Ph8EUAxhwVEdGlWusHENx0ci0z7wlI1kFMRn8EYUf5ELhzsm37BCHECiJ60PO8IxDMbpeyIaWcDQDt7e1Fv6ErpX7qOI4mopVSyo8qpZ4FgHg83kpEh5Yho8SLRHRyUMKY+f0ASlp0HkEl61YS1Wbb47Fhw4Y9AJZnP0gkEjMsyzqDmb8ppbyeiK72PM8f5dA3mDmw/p1ImPkeInoQwO0YJbA7FovVMfPniCiwmEQhxK4yx7dNan+UYEc5CXRDRDQabRJCPAbgXz3Puw5VcPMS0bzs1FFJ026+7z8C4EoieiIej7cCQDgcvoaZv4eAF/W11i9mH9pBEZisStatFKrRtguhvb39FaXUD5VSx2EovGDUhKPZhKG5NgFVJL7vtzPzoJTyw6P9Hg6HPw3gqexGnKD4czmvV6X1R752lA+BOqf6+vqLATyjlPpmkHLLSSaTmU5Ee4OQpZRaBuCKUCj022ySytO11t8JQvZIduzYsYWIZmNoSrIkHMd5T5DbtStZt1KoRtsuEq2U+hmALzDz8lgsVjfyR2Z+CsDMaqsNNAwz3wtgrIwRl2V/D4zBwcH1zDy7ubm5Nki5w1Rwf4xrR/kQqHMiok8xc1H1QSYLy7J2AmhFQNfC87xHmflyAD9l5ofyyURdKNnFyp3xeLy5VFlCiHkc4KJO0LqhQraSV6Ntl4JSahkR9QghTjjg++0AtkyfPj1n8Gwlkk6n/wPAGdFo9C1Z3xOJRAsRzdu/f3/Jwawj6ezs3ExEr8yaNassuzUrvT/GsqN8CDrOaS5KKFtORA0B6pIXqVTqOWaul1IGtnefmadgqGjYua7rjjqFEMA5VobD4b8JQM5FAJ4sXaO3yAxMN2ZeFYROAVB1tl0qzPyMZVkHPVSY+UFmDnqTz4SQjQf6VUNDw0Ujv7cs61JmfrAcNeKY+SEiKtuGhUrvj7HsKBdBj5x0Op3eVeThAkDJD7RC6ejoeJ2IFICPBiEvkUgsEEJ8C8BZWutzASxzXffsIGSPZGBg4EYAl5VSyC4Wi80jojiAjYEphkB1OxFAQdv7C6CgacdqtO2AOCju7+WXX74DwCLbttsmQZ+SYeZ7MJQxAsBQ9QEiOj+VSo2aWLVUMpnMrUS0uFzBq1XSH3nFj44kUOfEzE9HIpETiznWcZy/CyI/VDEw81UArhveyFAstm3Ptixrudb6S0qp9clk8vcAzmTmu7PVKQOjq6vrT8x8X01NzQ3FyohEIjcB+EHQb/UB6nYvhmKEAmXNmjV/IaJUW1tb3umEqtG2pZQ3lvhAPCmVSh2Udis7dXu1EGLMApD50NraOrWU44vF932PiNi27Q8BwKxZsz7FzM/kUwOpGNrb29/UWt9gWVZJ12usqrLl7o9y2VEugp7WWwPg44UeJKWMCyFkKpVaRUQ5819prQOt4JvN5nt1KBRaXuwN47ruaUKIp5j57mQy+fDw957nrWXmDxPRTVLKawJTGkBPT8+/APhkMVOHrut+jJlnb9u27X5mzqfoW0HXPQDdpnmedz+AnJHvRdgDM/MfIpFIIVMN1WjbL1uWtUJKWXDuRCnl8UR0SGdn56gBpEqpxwD0O47zNRRRUTuRSMyYMmXKGsdx8kopFDTMfJ9lWZcAABH9bTEbIQrpK9/3fwRgquM4Sws9DwAsWrSoubGx8ZlYLDZztN/L3B9ls6PxCNQ57dq161+ZOTGyimkubNs+HcC/pFKprxDRu5BH7JUQwsqnXSEopX4I4DdNTU1POY5zHvLsYNu23yWlvBnAj5n5877v//OBbXzf/wMzO0R0qZTyuwjoum/YsGEPM1/MzI9LKf8xT50t13W/wczf7O/v/z/d3d392YdmoNe9RN1u7e3tXQIgnc8DvRh7YOZHiejmfI+rRttWSt1PRHcQ0YpCplizmwWWA/gsxin02NfX9zkhxDlSyhXxePzQfOUnEokFoVDod0R0t+/7udYUQyhDPGZfX99PAHw8G4t4wvbt2/+zUBkF9hUPDg4uIaIvSyl/Fo1Gm/I9j+M4p9TU1PwPM3+1s7Nzx1jtytUf5bajsQjUOWWrxH7SsqzbXdf9znjTJolEYkG2jPeXd+3adWZ27ac2n7f4TCYTYeZIkLoDgFLqy1rrC4loqZRynZTys1LK4w/cBtnW1jYlkUgscl33XsuythLRvMHBwajv+78dR/ZL+/fvt4noQ1LKn2dLQJeM7/u/1VqfSURfkFL+ZywWmzdW23g8fpyUchUzu4ODg2euWbPmr2soQoic17PQ616kbgu11ouzUeh5UYw9+L5/JxENuK778Ghvo9FoNOw4znuG/65W2/Y87zta6/tqamo2uq5728j/6UDmz5/f4DjO0sbGxiSAb+UKHl+7du3O/v5+l4h2h8PhZ1zX/fR4pb5d141JKX9jWdYdmUzmQs/zck5DEVGEiAK/19euXbuTmVeHw+GfMPPyYtInFdpXq1ev7u7t7U0AaGxsbNzguu4ZGMe5SSk/IqVURHRFOp1erJT6r/Hkl7M/ymlHYxHo9NgwiUTiEMuyriCipcy8nYi2MfM2ADUA5hLR+5n5VQB3KKVWIOtVbdu2hRA/UkqNG3hp23abZVmr33jjjZrnnnsurxLjhSKl/DgRnc3MRwGYB2AAwBtENJuZMwBeYublAB4spDpqPB4/NBwOe8ycSqfTZ3d0dGwJQt9YLFYXDoe/SkQXMnMfET0D4FWttUVE7wWwAEA/Ed1wYFoR13Xv11q/6vv+uOl1ir3u+ehGRPsBXOd53opRdHva9/3vBa1XS0tL47Rp064VQvwdgPUAXgSwD8AsAA4z36WUumPkMdVq29FodHpDQ8PfA7gEwE4A3UTUzUNVkGdhqJzHXACPplKp28d7Qx8Nx3ESRHQ1gBiAdQC2E9EuZp4J4MjsffMnZr7Z9/1f5yvXdd0VANZnA58DxXGcpUKI72qtz/Z9v+CRUyl9Zdv26UKIK4molZm7iGgHM+8FMIuGMoMfwcwvENHXPM/rLFS3cvVHue1oJGVxTsNEo9FwJBKZE4lE5gKYy8wDRLRVa73Z9/1Xy3nuoGltbZ1aV1c3HUPp6QveeTKROI5zLIYSQh7OzL0A/rhv374XsqlGDiIajYbXrVuXRhFD71J1syxrU39//wtjFZPLxzmVSmtr69SGhoZjsnFVjUKIHVrr1eO9dFSxbYeyawdzATQzs2Dm7kwm093T0/NyqQ4xGo3WNzQ0LMhm454GYDuA55VSW/E2y6oRBNFotKm+vn4BgMOzefK2ZjKZF5LJZDcCSBZdxv4oqx0ZDBWPlHK54zjnT7YeBoNhYqmoYoMGw4EQUQszPzvZehgMhonFOCdDxZJdzJ2ze/fucgXiGgyGCsU4J0O5KDnx64wZM44FsMXMXxsM7zwmtEy74Z3BokWLmiORyOOvvPLKws2bNw+UIOoGAMuC0stgMFQPZuRkCJzVq1d3A9g0c+bMoiu/SinPJaL37du376CgZoPB8PbHOCdDWWDmpQA+K6W8oNBjs+UL7mTmC8qRJdpgMFQ+ZY1zMryzsW17thBiJYBVAL6RrT0zJm1tbVNqa2tvBHC21vpK3/cnJRGwwWCYfIxzMpSVlpaWxunTp18O4MsAntRarxdCdGutt2mtB0Kh0FHMfDQRHc3MHwHw8J49e27euHFj7ySrbjAYJhHjnAwTQjQara+rq1vkYD6MAAAAXElEQVQihDiKiOYw85xszrRNzLyJmTcR0ZpcoyuDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDBUAv8fkhaOx4mRFbYAAAAASUVORK5CYII=';
const LOGO_BUF = Buffer.from(LOGO_B64, 'base64');

// ── Gmail transport ──────────────────────────────────────────────────────────

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: GMAIL_USER,
    pass: GMAIL_APP_PASSWORD
  }
});

// ── Fireflies: fetch transcript ──────────────────────────────────────────────

async function fetchTranscript(meetingId) {
  const response = await fetch('https://api.fireflies.ai/graphql', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${FIREFLIES_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      query: `query GetTranscript($id: String!) {
        transcript(id: $id) {
          title
          sentences { raw_text }
        }
      }`,
      variables: { id: meetingId }
    })
  });

  const data = await response.json();
  const transcript = data?.data?.transcript;
  if (!transcript) throw new Error('Transcript not found for meeting ID: ' + meetingId);

  const text = transcript.sentences.map(s => s.raw_text).join(' ');
  return { title: transcript.title || 'AI Readiness Audit', text };
}

// ── Claude: analyse transcript ───────────────────────────────────────────────

async function analyseTranscript(transcriptText, context = {}) {
  const clientContext = context.clientName
    ? `Client: ${context.clientName}${context.position ? ` (${context.position})` : ''} | Company: ${context.companyName} | Industry: ${context.industry}${context.services ? ` | Services: ${context.services}` : ''}\n\n`
    : '';

  const prompt = `Do not use emojis. Do not use markdown formatting — no #, ##, **, or similar symbols. Write in plain professional text only, using capitalised section headings and clear paragraph breaks.

You are an expert AI implementation consultant with a direct, no-nonsense style. A client has just completed a 30-minute AI Readiness Audit session. You are preparing your internal working notes — a structured consultant briefing that will inform your recommendations and proposal.

${clientContext}

Write with confidence and specificity. You are a seasoned operator who has seen this pattern before, not an academic summarising a case study. Your observations should feel like a sharp consultant talking to a trusted colleague — direct, candid, occasionally wry. Call things what they are. If the business is a mess, say so. If the opportunity is obvious, say so. This is for your eyes only.

Analyse the transcript below and produce a detailed internal report with the following sections:

1. MEETING OVERVIEW
Client name and business. Industry. Your honest first impression of their AI readiness in 2-3 sentences — don't sanitise it.

2. CURRENT STATE ASSESSMENT
What tools and technology does the client currently use? What processes are manual or inefficient? Where is time being lost? How comfortable are they with technology and AI — and how does that shape the conversation ahead?

3. PAIN POINTS AND PRIORITIES
The 3-5 most significant problems or frustrations the client expressed. Quote directly where possible. Note which feel most urgent — and which they may not have fully articulated yet.

4. AI READINESS SCORE
Score the client across these 6 dimensions (1-5 scale with brief rationale for each):
- Technology Infrastructure
- Data and Process Documentation
- Team Capability and Openness
- Budget and Investment Appetite
- Decision-Making Speed
- Overall Strategic Clarity
Overall readiness score out of 30.

5. TOP AUTOMATION OPPORTUNITIES
List the 5-7 highest-impact AI automation opportunities specific to this client. For each: what it automates, estimated time saved per week, complexity (low/medium/high), and ROI category. Be specific — generic observations are useless here.

6. QUICK WINS
The 3 things that could be implemented within 30 days with minimal disruption and visible impact. These should feel genuinely achievable, not aspirational fluff.

7. CONSULTANT NOTES
Buying signals, hesitations, objections raised, red flags, or anything that should shape how you position the proposal. Be completely candid — this is your private read on the client and the room.

TRANSCRIPT:
${transcriptText}`;

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }]
    })
  });

  const data = await response.json();
  if (!data?.content?.[0]?.text) throw new Error('Claude returned no content: ' + JSON.stringify(data));
  return data.content[0].text;
}

// ── Claude: generate proposal ────────────────────────────────────────────────

async function generateProposal(analysisText) {
  const prompt = `Do not use emojis. Do not use markdown formatting — no #, ##, **, or similar symbols. Write in plain professional text only, using capitalised section headings and clear paragraph breaks.

You are an expert AI implementation consultant preparing a tailored proposal for a prospective client following their AI Readiness Audit session.

Using the internal analysis report below, write a professional client-facing proposal document. The tone should feel like a senior advisor who has done their homework — authoritative, warm, and specific. The client should feel genuinely understood, not processed. Write as someone who has diagnosed their situation precisely and has a clear plan for what to build. Avoid corporate filler. Every sentence should earn its place.

Structure the proposal as follows:

1. EXECUTIVE SUMMARY
2-3 paragraphs. Acknowledge what you heard in the audit. Name the core challenge without sugarcoating it. Position AI implementation as the specific lever that changes the trajectory — not AI in the abstract, but the work you will do together.

2. YOUR SITUATION
A direct, empathetic summary of where the client is today. Make them feel deeply understood. Use specifics from the audit. This section should feel like you were paying close attention — because you were.

3. WHAT WE WILL BUILD
The specific AI systems and automations recommended. Name the tools. Describe what each does in plain language a smart business owner will immediately grasp. State the business outcome each one delivers — not the feature, the result.

4. WHAT THIS MEANS FOR YOUR BUSINESS
Quantify where possible: time saved per week, estimated revenue impact, cost reduction, client experience improvement. Be specific. Round numbers are fine. Vague promises are not.

5. IMPLEMENTATION ROADMAP
A simple 30/60/90 day timeline. What gets built in each phase. Keep it practical and sequenced — early wins first, complexity later.

6. YOUR INVESTMENT
Option 10 AI Growth Accelerator: $5,000/month over 3 months ($15,000 total). Frame as an investment with a clear return. Note that the $497 Audit fee is credited against Month 1 if they proceed within 14 days.

7. NEXT STEPS
One clear action: reply to book a 45-minute proposal walkthrough call. Make it easy and low-friction.

INTERNAL ANALYSIS:
${analysisText}`;

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }]
    })
  });

  const data = await response.json();
  if (!data?.content?.[0]?.text) throw new Error('Claude returned no content: ' + JSON.stringify(data));
  return data.content[0].text;
}

// ── Claude: generate tailored questionnaire ──────────────────────────────────

async function generateQuestionnaire(clientName, companyName, industry, position, services) {
  const prompt = `Output ONLY sections and questions — no introduction, no closing note, no extra commentary. Use this exact format:

SECTION 1 - [TITLE IN CAPS]

[MUST] Question text here
[OPTIONAL] Question text here

SECTION 2 - [TITLE IN CAPS]

[MUST] Question text here
...

Rules:
- Every question must begin with either [MUST] or [OPTIONAL] on its own line
- Section headers must follow the format: SECTION N - TITLE IN CAPS
- No markdown, no bullets, no numbering, no emojis
- Each question is a single line of plain text

Client: ${clientName}
Position: ${position}
Company: ${companyName}
Industry: ${industry}
Services offered: ${services}

Produce exactly 10 sections and 54 questions. Mark approximately 30 as [MUST] and 24 as [OPTIONAL]. Use your judgment — MUST questions are the highest-impact ones that must be covered in the session. OPTIONAL questions add useful depth but can be skipped if time is short. Aim for 3 MUST and 2-3 OPTIONAL per section. Questions must feel like they were written by someone who knows this industry well.

Important: the client's position is ${position}. Tailor questions accordingly — do not assume they are the founder or sole decision-maker. If they are a manager or employee rather than an owner, adjust questions about strategy, investment appetite, and decision-making to reflect their likely scope of influence. The services they provide are: ${services} — use this to sharpen every industry-specific question, particularly in Section 5.

SECTION 1 - YOUR BUSINESS AT A GLANCE (6 questions)
Cover: how long they have been operating and whether it has evolved from its original form; team structure and what each person broadly handles; primary revenue streams specific to their stated services; what a typical working week actually looks like and where most time goes; their primary market or client base; the one thing keeping them up at night right now.

SECTION 2 - YOUR TECH STACK (6 questions)
Cover: the main software and platforms they rely on day to day (CRM, industry-specific tools, communication tools, document and signing tools); any AI tools they already use, even informally; how well their tools connect — do they flow cleanly or require workarounds; whether their current setup could handle a significant increase in client volume without breaking.

SECTION 3 - LEAD GENERATION AND NEW BUSINESS (6 questions)
Cover: top lead sources ranked by volume and separately by quality; how quickly they make first contact with a new inbound lead; roughly how many leads per month across all sources; whether they have a written lead qualification process; the biggest bottleneck in winning new business; whether doubling leads tomorrow would break their current setup.

SECTION 4 - LEAD NURTURE AND FOLLOW-UP (5 questions)
Cover: whether a structured drip or nurture sequence runs on autopilot; how they handle leads that went quiet and reactivation at 3, 6, and 12 months; how long leads take to convert or go cold; what happens when someone contacts them outside business hours; whether they use AI to write follow-up messages or draft replies.

SECTION 5 - DAY-TO-DAY OPERATIONS (6 questions)
Tailor these specifically to a ${industry}. Think carefully about their version of client work delivery. Cover the admin tasks that repeat every week without fail, the industry-specific software or workflow they most likely use, where time genuinely disappears, where things fall through the cracks, and the most repetitive task they would happily delegate to a system. These must feel written by someone who has worked inside this type of business.

SECTION 6 - PAST CLIENTS AND DATABASE (5 questions)
Cover: how many past clients and contacts are in their database; when each last heard from them personally rather than via mass comms; whether there is a structured plan for real ongoing contact; what percentage of business comes from referrals or repeat clients; whether they have ever segmented their database for targeted outreach and how practical that is currently.

SECTION 7 - MARKETING AND CONTENT (5 questions)
Cover: how consistently they show up on social media and on which platforms; who creates the content and how long it takes each week; whether they produce video and what type; whether they run paid advertising and what the results look like; what they would produce more of if the time cost dropped to almost nothing.

SECTION 8 - ADMIN AND TIME (5 questions)
Cover: total hours worked per week and what percentage is genuinely income-generating versus administrative; the task that drains their energy most every week; the task that gets pushed off week after week despite mattering; what falls apart when they take time off; what they would do with ten recovered hours a week.

SECTION 9 - AI AND TECHNOLOGY READINESS (5 questions)
Cover: honest comfort level with new technology and how they typically adopt new tools; biggest concern or hesitation about AI in their business; whether their team would resist new systems and how that shows up; where they feel strongly a human must always be present and automation should not go; whether they have tried AI tools before that did not stick and why.

SECTION 10 - GOALS AND PRIORITIES (5 questions)
Cover: top three business goals for the next twelve months; the single biggest constraint preventing them from hitting those goals; where the most realistic untapped revenue opportunity sits right now; whether they are primarily trying to grow volume, grow margin, or recover personal time; what success looks like specifically in six months in terms of how the business feels and operates day to day.`;

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }]
    })
  });

  const data = await response.json();
  if (!data?.content?.[0]?.text) throw new Error('Claude returned no content for questionnaire');
  return data.content[0].text;
}

// ── Questionnaire docx builder ───────────────────────────────────────────────

function parseQuestionnaire(text) {
  const sections = [];
  let current = null;
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line) continue;
    if (/^SECTION\s+\d+\s*[-—]/i.test(line)) {
      current = { title: line.replace(/^SECTION\s+\d+\s*[-—]\s*/i, '').trim(), questions: [] };
      sections.push(current);
    } else if (line.startsWith('[MUST]') && current) {
      current.questions.push({ type: 'must', text: line.replace('[MUST]', '').trim() });
    } else if (line.startsWith('[OPTIONAL]') && current) {
      current.questions.push({ type: 'optional', text: line.replace('[OPTIONAL]', '').trim() });
    }
  }
  return sections;
}

async function buildQuestionnaireDocx(questionnaireText, clientName, companyName) {
  const firstName  = clientName.split(' ')[0];
  const sections   = parseQuestionnaire(questionnaireText);

  const NAVY     = '1A2744';
  const GOLD     = 'C8A951';
  const MUST_BG  = 'EEF2F7';
  const OPT_BG   = 'FAFAFA';
  const LINE_CLR = 'CCCCCC';

  const none   = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  const noBdr  = { top: none, bottom: none, left: none, right: none };
  const thin   = { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' };
  const thinBdr= { top: thin, bottom: thin, left: thin, right: thin };

  const CONTENT = 9360; // US Letter 1" margins
  const BADGE   = 520;
  const BODY_W  = CONTENT - BADGE;

  const sp = (after = 100) =>
    new Paragraph({ spacing: { before: 0, after }, children: [new TextRun('')] });

  const sectionBanner = title =>
    new Table({
      width: { size: CONTENT, type: WidthType.DXA },
      columnWidths: [CONTENT],
      rows: [new TableRow({ children: [new TableCell({
        borders: thinBdr,
        width: { size: CONTENT, type: WidthType.DXA },
        shading: { fill: NAVY, type: ShadingType.CLEAR },
        margins: { top: 140, bottom: 140, left: 200, right: 200 },
        children: [new Paragraph({ children: [
          new TextRun({ text: title, font: 'Arial', size: 20, bold: true, color: GOLD })
        ]})]
      })]})],
    });

  const questionBlock = (num, q) => {
    const isMust    = q.type === 'must';
    const badgeFill = isMust ? NAVY : '8B9DB5';
    const bodyFill  = isMust ? MUST_BG : OPT_BG;
    const labelTxt  = isMust ? 'PRIORITY' : 'WORTH COVERING';
    const labelClr  = isMust ? NAVY : 'AAAAAA';
    const qClr      = isMust ? '111111' : '555555';

    return new Table({
      width: { size: CONTENT, type: WidthType.DXA },
      columnWidths: [BADGE, BODY_W],
      rows: [new TableRow({ children: [
        // Number badge
        new TableCell({
          borders: noBdr,
          width: { size: BADGE, type: WidthType.DXA },
          shading: { fill: badgeFill, type: ShadingType.CLEAR },
          margins: { top: 120, bottom: 0, left: 80, right: 80 },
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: String(num), font: 'Arial', size: 20, bold: true, color: 'FFFFFF' })]
          })]
        }),
        // Question + notes
        new TableCell({
          borders: noBdr,
          width: { size: BODY_W, type: WidthType.DXA },
          shading: { fill: bodyFill, type: ShadingType.CLEAR },
          margins: { top: 100, bottom: 120, left: 180, right: 140 },
          children: [
            new Paragraph({
              spacing: { before: 0, after: 40 },
              children: [new TextRun({ text: labelTxt, font: 'Arial', size: 14, bold: true, color: labelClr })]
            }),
            new Paragraph({
              spacing: { before: 0, after: 120 },
              children: [new TextRun({ text: q.text, font: 'Arial', size: 19, bold: isMust, color: qClr })]
            }),
            new Paragraph({
              spacing: { before: 0, after: 40 },
              children: [new TextRun({ text: 'Your notes:', font: 'Arial', size: 15, color: 'AAAAAA' })]
            }),
            new Paragraph({
              spacing: { before: 0, after: 0 },
              border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: LINE_CLR } },
              children: [new TextRun({ text: ' ', font: 'Arial', size: 18 })]
            }),
            new Paragraph({
              spacing: { before: 80, after: 0 },
              border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: LINE_CLR } },
              children: [new TextRun({ text: ' ', font: 'Arial', size: 18 })]
            }),
          ]
        })
      ]})]
    });
  };

  const children = [];

  // ── Title block ────────────────────────────────────────────────────────────
  children.push(new Paragraph({
    spacing: { before: 200, after: 60 },
    children: [new TextRun({ text: 'AI Readiness Audit', font: 'Arial', size: 48, bold: true, color: NAVY })]
  }));
  children.push(new Paragraph({
    spacing: { before: 0, after: 60 },
    children: [new TextRun({ text: 'Session Preparation Guide', font: 'Arial', size: 26, color: GOLD })]
  }));
  children.push(new Paragraph({
    spacing: { before: 0, after: 200 },
    children: [new TextRun({ text: `${clientName}  —  ${companyName}`, font: 'Arial', size: 20, color: '888888' })]
  }));

  // ── Intro box ──────────────────────────────────────────────────────────────
  children.push(new Table({
    width: { size: CONTENT, type: WidthType.DXA },
    columnWidths: [CONTENT],
    rows: [new TableRow({ children: [new TableCell({
      borders: thinBdr,
      width: { size: CONTENT, type: WidthType.DXA },
      shading: { fill: MUST_BG, type: ShadingType.CLEAR },
      margins: { top: 180, bottom: 180, left: 240, right: 240 },
      children: [
        new Paragraph({
          spacing: { before: 0, after: 100 },
          children: [new TextRun({ text: `Hi ${firstName},`, font: 'Arial', size: 21, bold: true, color: NAVY })]
        }),
        new Paragraph({
          spacing: { before: 0, after: 100 },
          children: [new TextRun({
            text: `This document is your preparation guide for our upcoming AI Readiness Audit session. Work through the questions beforehand and jot down your thoughts in the notes space below each one — bullet points are fine. There are no wrong answers.`,
            font: 'Arial', size: 20, color: '333333'
          })]
        }),
        new Paragraph({
          spacing: { before: 0, after: 100 },
          children: [new TextRun({
            text: `Please save this document to your computer before filling it in — it will not be editable until you do. Once saved, click into the notes space below any question and start typing.`,
            font: 'Arial', size: 20, bold: true, color: NAVY
          })]
        }),
        new Paragraph({
          spacing: { before: 0, after: 100 },
          children: [new TextRun({
            text: `Bring the document to our Zoom call. We will work through the questions together — you talk through your answers and we will explore them in conversation. You do not need to send anything back to me.`,
            font: 'Arial', size: 20, color: '333333'
          })]
        }),
        new Paragraph({
          spacing: { before: 0, after: 60 },
          children: [
            new TextRun({ text: 'PRIORITY  ', font: 'Arial', size: 19, bold: true, color: NAVY }),
            new TextRun({ text: 'questions are our must-covers for the session.  ', font: 'Arial', size: 19, color: '333333' }),
            new TextRun({ text: 'WORTH COVERING  ', font: 'Arial', size: 19, bold: true, color: '888888' }),
            new TextRun({ text: 'questions add real value — we will get to them if time allows.', font: 'Arial', size: 19, color: '333333' }),
          ]
        }),
      ]
    })]})],
  }));

  children.push(sp(240));

  // ── Sections and questions ─────────────────────────────────────────────────
  let num = 0;
  for (const section of sections) {
    children.push(sectionBanner(section.title));
    children.push(sp(120));
    for (const q of section.questions) {
      num++;
      children.push(questionBlock(num, q));
      children.push(sp(120));
    }
    children.push(sp(160));
  }

  // ── Closing ────────────────────────────────────────────────────────────────
  children.push(new Paragraph({
    spacing: { before: 120, after: 0 },
    border: { top: { style: BorderStyle.SINGLE, size: 2, color: 'DDDDDD' } },
    children: []
  }));
  children.push(sp(120));
  children.push(new Paragraph({
    children: [new TextRun({ text: `Looking forward to our conversation, ${firstName}. See you on the call.`, font: 'Arial', size: 20, color: '555555', italics: true })]
  }));
  children.push(sp(60));
  children.push(new Paragraph({
    children: [new TextRun({ text: 'Frankie  |  Option 10  |  frankie@option10.com', font: 'Arial', size: 18, color: 'AAAAAA' })]
  }));

  const doc = new Document({
    styles: { default: { document: { run: { font: 'Arial', size: 20 } } } },
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }
        }
      },
      headers: {
        default: new Header({ children: [
          new Table({
            width: { size: CONTENT, type: WidthType.DXA },
            columnWidths: [5400, 3960],
            rows: [new TableRow({ children: [
              new TableCell({ borders: noBdr, width: { size: 5400, type: WidthType.DXA },
                children: [new Paragraph({ children: [
                  new ImageRun({
                    type: 'png',
                    data: LOGO_BUF,
                    transformation: { width: 127, height: 60 },
                    altText: { title: 'Option 10', description: 'Option 10 logo', name: 'Option10Logo' }
                  })
                ]})]
              }),
              new TableCell({ borders: noBdr, width: { size: 3960, type: WidthType.DXA },
                children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [
                  new TextRun({ text: 'AI Readiness Audit — Preparation Guide', font: 'Arial', size: 18, color: '999999' })
                ]})]
              })
            ]})]
          }),
          new Paragraph({
            spacing: { before: 60, after: 0 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: NAVY } },
            children: []
          })
        ]})
      },
      footers: {
        default: new Footer({ children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          border: { top: { style: BorderStyle.SINGLE, size: 2, color: 'DDDDDD' } },
          spacing: { before: 80, after: 0 },
          children: [
            new TextRun({ text: 'Option 10  |  Confidential  |  Page ', font: 'Arial', size: 16, color: 'AAAAAA' }),
            new TextRun({ children: [PageNumber.CURRENT], font: 'Arial', size: 16, color: 'AAAAAA' })
          ]
        })]})
      },
      children
    }]
  });

  return Packer.toBuffer(doc);
}

// ── In-memory stores ─────────────────────────────────────────────────────────
// Pending clients — keyed by normalised full name, consumed when their Zoom session is processed
// Supports multiple simultaneous audits in the pipeline
const pendingClients = new Map();

// Active audits — keyed by Fireflies meeting ID
// Maps meetingId -> { title, clientName, companyName, industry, transcript, analysis }
const auditStore = {};

// ── Routes ───────────────────────────────────────────────────────────────────

// Token protection — only requests with ?token=ACCESS_TOKEN can access the form
function requireToken(req, res, next) {
  const token = req.query.token || req.body?.token;
  if (token === ACCESS_TOKEN) return next();
  res.status(403).send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Access Restricted</title>
  <style>
    body { font-family: Arial, sans-serif; background: #f0f2f5; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
    .box { background: #fff; border-radius: 10px; padding: 48px 40px; text-align: center; max-width: 420px; box-shadow: 0 4px 24px rgba(0,0,0,0.10); }
    h2 { color: #1A2744; margin-bottom: 12px; }
    p { color: #666; font-size: 15px; }
  </style>
</head>
<body>
  <div class="box">
    <h2>Access Restricted</h2>
    <p>This page requires an access token. Please use the link provided by Option 10.</p>
  </div>
</body>
</html>`);
}

const CARD_STYLES = `
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; background: #f0f2f5; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 24px; }
    .card { background: #fff; border-radius: 10px; overflow: hidden; width: 100%; max-width: 520px; box-shadow: 0 4px 24px rgba(0,0,0,0.10); }
    .header { background: #1A2744; padding: 28px 32px; }
    .header h1 { color: #C8A951; font-size: 22px; font-weight: bold; letter-spacing: 0.3px; }
    .header p { color: #a0aec0; font-size: 14px; margin-top: 4px; }
    .body { padding: 32px; }
    .field { margin-bottom: 22px; }
    label { display: block; font-size: 14px; font-weight: bold; color: #1A2744; margin-bottom: 8px; }
    input { width: 100%; padding: 12px 14px; border: 1.5px solid #dde1e9; border-radius: 6px; font-size: 15px; color: #222; outline: none; transition: border-color 0.2s; background: #fff; }
    input:focus { border-color: #1A2744; }
    input::placeholder { color: #b0b8c9; }
    .btn { width: 100%; padding: 14px; background: #1A2744; color: #C8A951; font-size: 16px; font-weight: bold; border: none; border-radius: 6px; cursor: pointer; letter-spacing: 0.4px; transition: opacity 0.2s; margin-top: 6px; }
    .btn:hover { opacity: 0.88; }
    .body p { color: #444; font-size: 15px; line-height: 1.6; margin-bottom: 12px; }
    .body strong { color: #1A2744; }
    .footer { padding: 16px 32px; border-top: 1px solid #f0f2f5; text-align: center; }
    .footer p { font-size: 12px; color: #b0b8c9; }
`;

// Dashboard — new audit entry form
app.get('/', requireToken, (req, res) => {
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Option 10 — AI Audit System</title>
  <style>${CARD_STYLES}</style>
</head>
<body>
  <div class="card">
    <div class="header">
      <img src="data:image/png;base64,${LOGO_B64}" alt="Option 10" style="height:52px;display:block;margin-bottom:10px">
      <p>AI Readiness Audit — New Session</p>
    </div>
    <div class="body">
      <form action="/start" method="POST">
        <input type="hidden" name="token" value="${req.query.token || ''}">
        <div class="field">
          <label for="clientName">Client Name</label>
          <input type="text" id="clientName" name="clientName" placeholder="e.g. Sarah Johnson" required>
        </div>
        <div class="field">
          <label for="companyName">Company / Business Name</label>
          <input type="text" id="companyName" name="companyName" placeholder="e.g. Apex Legal" required>
        </div>
        <div class="field">
          <label for="industry">Industry</label>
          <input type="text" id="industry" name="industry" placeholder="e.g. Employment law firm" required>
        </div>
        <div class="field">
          <label for="position">Position within the Company</label>
          <input type="text" id="position" name="position" placeholder="e.g. Managing Partner, Practice Manager, Director" required>
        </div>
        <div class="field">
          <label for="services">Services They Offer</label>
          <input type="text" id="services" name="services" placeholder="e.g. Divorce, child custody, prenuptial agreements, adoption" required>
        </div>
        <div class="field">
          <label for="clientEmail">Client Email</label>
          <input type="email" id="clientEmail" name="clientEmail" placeholder="e.g. sarah@apexlegal.com" required>
        </div>
        <button type="submit" class="btn">Send Questionnaire</button>
      </form>
    </div>
    <div class="footer">
      <p>Option 10 AI Audit System</p>
    </div>
  </div>
</body>
</html>`);
});

// Handle form submission — generate questionnaire, email client, store pending context
app.post('/start', requireToken, async (req, res) => {
  const { clientName, companyName, industry, position, services, clientEmail } = req.body;

  if (!clientName || !companyName || !industry || !position || !services || !clientEmail) {
    return res.status(400).send('All fields are required.');
  }

  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Option 10 — Confirmed</title>
  <style>${CARD_STYLES}</style>
</head>
<body>
  <div class="card">
    <div class="header">
      <img src="data:image/png;base64,${LOGO_B64}" alt="Option 10" style="height:52px;display:block;margin-bottom:10px">
      <p>AI Readiness Audit — Session Confirmed</p>
    </div>
    <div class="body">
      <p>Generating a tailored questionnaire for <strong>${clientName}</strong> (${position}) at <strong>${companyName}</strong>.</p>
      <p>It will be emailed to <strong>${clientEmail}</strong> in approximately 30 seconds.</p>
      <p>You will receive a confirmation once it has been sent.</p>
      <p style="margin-top:16px;padding:12px 16px;background:#f5f0e0;border-left:3px solid #C8A951;font-size:14px;color:#555">When you schedule the Zoom session, name the meeting: <strong style="color:#1A2744">AI Audit — ${clientName}</strong></p>
    </div>
    <div class="footer">
      <p>Option 10 AI Audit System</p>
    </div>
  </div>
</body>
</html>`);

  console.log(`New AI Audit: ${clientName} — ${companyName} (${industry})`);

  try {
    const questionnaire = await generateQuestionnaire(clientName, companyName, industry, position, services);

    pendingClients.set(clientName.toLowerCase().trim(), { clientName, companyName, industry, position, services, clientEmail });
    console.log(`Pending client added: ${clientName} — ${companyName} (${pendingClients.size} in pipeline)`);

    const firstName = clientName.split(' ')[0];
    const docxBuffer = await buildQuestionnaireDocx(questionnaire, clientName, companyName);
    const docxFilename = `${clientName.toLowerCase().replace(/\s+/g, '-')}-ai-audit-prep-guide.docx`;

    await transporter.sendMail({
      from: GMAIL_USER,
      to: clientEmail,
      bcc: NOTIFY_EMAIL,
      subject: `Your AI Readiness Audit — Session Preparation Guide`,
      html: `
        <div style="font-family:Arial;max-width:600px;margin:0 auto">
          <div style="background:#1A2744;padding:24px 32px">
            <img src="data:image/png;base64,${LOGO_B64}" alt="Option 10" style="height:48px;display:block;margin-bottom:8px">
            <p style="color:#a0aec0;font-size:13px;margin:0">AI Readiness Audit</p>
          </div>
          <div style="padding:32px;background:#fff;line-height:1.7;color:#333;font-size:15px">
            <p>Hi ${firstName},</p>
            <p>Looking forward to our session. I've attached your preparation guide — open it, work through the questions at your own pace, and jot any thoughts in the notes space below each one.</p>
            <p>A few things worth knowing:</p>
            <ul style="padding-left:20px">
              <li><strong>Save the document to your computer first</strong> — it will not be editable until you do</li>
              <li>Bring the document to our Zoom call — we will work through your answers together in conversation</li>
              <li>Questions marked <strong>PRIORITY</strong> are our must-covers. <strong>WORTH COVERING</strong> ones add real value — we will get to them if time allows</li>
              <li>Bullet points are fine. There are no wrong answers</li>
              <li>You do not need to send anything back — just show up with your notes</li>
            </ul>
            <p>See you on the call.</p>
            <p style="margin-top:24px">Frankie<br><span style="color:#999;font-size:13px">Option 10 | frankie@option10.com</span></p>
          </div>
          <div style="padding:16px 32px;background:#f8f8f8;text-align:center">
            <p style="font-size:12px;color:#b0b0b0">Option 10 AI Readiness Audit</p>
          </div>
        </div>
      `,
      attachments: [{
        filename: docxFilename,
        content: docxBuffer,
        contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      }]
    });

    console.log(`Questionnaire emailed to ${clientEmail}`);

    await transporter.sendMail({
      from: GMAIL_USER,
      to: NOTIFY_EMAIL,
      subject: `Questionnaire Sent — ${clientName}, ${companyName}`,
      html: `
        <p><strong>The pre-audit questionnaire has been sent.</strong></p>
        <p><strong>Client:</strong> ${clientName} — ${position}</p>
        <p><strong>Company:</strong> ${companyName}</p>
        <p><strong>Industry:</strong> ${industry}</p>
        <p><strong>Services:</strong> ${services}</p>
        <p><strong>Sent to:</strong> ${clientEmail}</p>
        <p>The system is waiting for their Zoom session. When you schedule the call, name the Zoom meeting: <strong>AI Audit — ${clientName}</strong> — this is how the system matches the recording to the right client.</p>
        <br><p style="color:#888">Option 10 AI Audit System</p>
      `
    });

    console.log(`Confirmation sent to ${NOTIFY_EMAIL}`);

    if (TRACKER_WEBHOOK_URL) {
      fetch(TRACKER_WEBHOOK_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clientName, companyName, industry, position, services, clientEmail })
      }).then(() => console.log('Tracker updated'))
        .catch(err => console.error('Tracker error:', err.message));
    }
  } catch (err) {
    console.error('Start error:', err.message);
  }
});

// Phase 1: Fireflies webhook fires when meeting is transcribed
app.post('/webhook/fireflies', async (req, res) => {
  res.sendStatus(200); // acknowledge immediately

  const meetingId = req.body.meeting_id || req.body.meetingId;
  if (!meetingId) {
    console.error('No meeting_id in webhook payload:', req.body);
    return;
  }

  console.log('Phase 1: Received webhook for meeting:', meetingId);

  try {
    // Ignore webhook if no audits are currently in the pipeline
    if (pendingClients.size === 0) {
      console.log('Webhook received but no audits in pipeline — ignoring:', meetingId);
      return;
    }

    const { title, text } = await fetchTranscript(meetingId);

    // Match the meeting title against pending clients by name
    // Meeting should be named e.g. "AI Audit — Lex Figueroa" or "Lex Figueroa AI Audit"
    let matchedKey = null;
    let context = {};
    const titleLower = (title || '').toLowerCase();

    for (const [key, client] of pendingClients.entries()) {
      const nameParts = key.split(' ').filter(p => p.length > 1);
      if (nameParts.length >= 2 && nameParts.every(part => titleLower.includes(part))) {
        matchedKey = key;
        context = client;
        break;
      }
      // Fallback: full name as substring
      if (titleLower.includes(key)) {
        matchedKey = key;
        context = client;
        break;
      }
    }

    if (matchedKey) {
      console.log(`Phase 1: Matched meeting "${title}" to pending client: ${context.clientName}`);
      pendingClients.delete(matchedKey);
    } else {
      console.log(`Phase 1: No client match found for meeting "${title}" — processing with title only`);
    }

    const displayTitle = context.clientName
      ? `${context.clientName} — ${context.companyName}`
      : title;

    auditStore[meetingId] = {
      title: displayTitle,
      clientName: context.clientName || '',
      companyName: context.companyName || '',
      industry: context.industry || '',
      position: context.position || '',
      services: context.services || '',
      transcript: text,
      analysis: null
    };

    console.log('Phase 1: Transcript fetched for:', displayTitle);

    await transporter.sendMail({
      from: GMAIL_USER,
      to: NOTIFY_EMAIL,
      subject: `AI Audit for ${displayTitle} is Ready`,
      html: `
        <p><strong>A new AI Readiness Audit transcript is ready.</strong></p>
        <p><strong>Client:</strong> ${displayTitle}</p>
        ${context.industry ? `<p><strong>Industry:</strong> ${context.industry}</p>` : ''}
        <p><strong>Transcript length:</strong> ${text.split(' ').length} words</p>
        <p><strong>Meeting ID:</strong> ${meetingId}</p>
        <p>When you are ready to run the AI analysis, click the button below:</p>
        <p><a href="https://ai-audit-server-production-b423.up.railway.app/analyse/${meetingId}" style="background:#1A2744;color:#C8A951;padding:12px 24px;text-decoration:none;font-weight:bold;border-radius:4px">Generate Consultant Briefing</a></p>
        <br><p style="color:#888">Option 10 AI Audit System</p>
      `
    });

    console.log('Phase 1: Notification email sent for:', displayTitle);
  } catch (err) {
    console.error('Phase 1 error:', err.message);
  }
});

// Phase 2: GET version so you can click a link in the email
app.get('/analyse/:meetingId', async (req, res) => {
  res.send(`<html><body style="font-family:Arial;padding:40px">
    <h2>Triggering analysis...</h2>
    <p>The consultant briefing is being generated. You will receive an email in approximately 60 seconds.</p>
    <p style="color:#888">Option 10 AI Audit System</p>
  </body></html>`);
  const { meetingId } = req.params;
  const audit = auditStore[meetingId];
  if (!audit) { console.error('Phase 2 GET: No audit found for meeting:', meetingId); return; }
  try {
    const analysis = await analyseTranscript(audit.transcript, { clientName: audit.clientName, companyName: audit.companyName, industry: audit.industry, position: audit.position, services: audit.services });
    auditStore[meetingId].analysis = analysis;
    await transporter.sendMail({
      from: GMAIL_USER, to: NOTIFY_EMAIL,
      subject: `AI Analysis for ${audit.title} is Ready`,
      html: `<p><strong>Your AI Readiness Analysis is complete.</strong></p><p><strong>Client:</strong> ${audit.title}</p><p><strong>Meeting ID:</strong> ${meetingId}</p><hr><pre style="font-family:Arial;font-size:14px;white-space:pre-wrap">${analysis}</pre><hr><p>When ready for the client proposal, click below:</p><p><a href="https://ai-audit-server-production-b423.up.railway.app/propose/${meetingId}" style="background:#1A2744;color:#C8A951;padding:12px 24px;text-decoration:none;font-weight:bold;border-radius:4px">Generate Client Proposal</a></p><br><p style="color:#888">Option 10 AI Audit System</p>`
    });
    console.log('Phase 2 GET: Analysis email sent for:', audit.title);
  } catch (err) { console.error('Phase 2 GET error:', err.message); }
});

// Phase 2: POST version (keep for backwards compatibility)
app.post('/analyse/:meetingId', async (req, res) => {
  res.sendStatus(200);

  const { meetingId } = req.params;
  const audit = auditStore[meetingId];

  if (!audit) {
    console.error('Phase 2: No audit found for meeting:', meetingId);
    return;
  }

  console.log('Phase 2: Running analysis for:', audit.title);

  try {
    const analysis = await analyseTranscript(audit.transcript, { clientName: audit.clientName, companyName: audit.companyName, industry: audit.industry, position: audit.position, services: audit.services });
    auditStore[meetingId].analysis = analysis;

    await transporter.sendMail({
      from: GMAIL_USER,
      to: NOTIFY_EMAIL,
      subject: `AI Analysis for ${audit.title} is Ready`,
      html: `
        <p><strong>Your AI Readiness Analysis is complete.</strong></p>
        <p><strong>Client:</strong> ${audit.title}</p>
        <p><strong>Meeting ID:</strong> ${meetingId}</p>
        <hr>
        <pre style="font-family:Arial;font-size:14px;white-space:pre-wrap">${analysis}</pre>
        <hr>
        <p>When you are ready to generate the client proposal, reply to this email with the single word:</p>
        <p><strong>PROPOSE</strong></p>
        <br><p style="color:#888">Option 10 AI Audit System</p>
      `
    });

    console.log('Phase 2: Analysis email sent for:', audit.title);
  } catch (err) {
    console.error('Phase 2 error:', err.message);
  }
});

// Phase 3: GET version so you can click a link in the email
app.get('/propose/:meetingId', async (req, res) => {
  res.send(`<html><body style="font-family:Arial;padding:40px">
    <h2>Generating client proposal...</h2>
    <p>The proposal is being written. You will receive an email in approximately 60 seconds.</p>
    <p style="color:#888">Option 10 AI Audit System</p>
  </body></html>`);
  const { meetingId } = req.params;
  const audit = auditStore[meetingId];
  if (!audit || !audit.analysis) { console.error('Phase 3 GET: No analysis found for meeting:', meetingId); return; }
  try {
    const proposal = await generateProposal(audit.analysis);
    await transporter.sendMail({
      from: GMAIL_USER, to: NOTIFY_EMAIL,
      subject: `AI Proposal for ${audit.title} is Ready`,
      html: `<p><strong>The client proposal draft is complete.</strong></p><p><strong>Client:</strong> ${audit.title}</p><hr><pre style="font-family:Arial;font-size:14px;white-space:pre-wrap">${proposal}</pre><hr><p>Review and edit before sending to the client.</p><br><p style="color:#888">Option 10 AI Audit System</p>`
    });
    console.log('Phase 3 GET: Proposal email sent for:', audit.title);
  } catch (err) { console.error('Phase 3 GET error:', err.message); }
});

// Phase 3: POST version (keep for backwards compatibility)
app.post('/propose/:meetingId', async (req, res) => {
  res.sendStatus(200);

  const { meetingId } = req.params;
  const audit = auditStore[meetingId];

  if (!audit || !audit.analysis) {
    console.error('Phase 3: No analysis found for meeting:', meetingId);
    return;
  }

  console.log('Phase 3: Generating proposal for:', audit.title);

  try {
    const proposal = await generateProposal(audit.analysis);

    await transporter.sendMail({
      from: GMAIL_USER,
      to: NOTIFY_EMAIL,
      subject: `AI Proposal for ${audit.title} is Ready`,
      html: `
        <p><strong>The client proposal draft is complete.</strong></p>
        <p><strong>Client:</strong> ${audit.title}</p>
        <hr>
        <pre style="font-family:Arial;font-size:14px;white-space:pre-wrap">${proposal}</pre>
        <hr>
        <p>Review and edit before sending to the client.</p>
        <br><p style="color:#888">Option 10 AI Audit System</p>
      `
    });

    console.log('Phase 3: Proposal email sent for:', audit.title);
  } catch (err) {
    console.error('Phase 3 error:', err.message);
  }
});

// ── Start ────────────────────────────────────────────────────────────────────

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`AI Audit Server listening on port ${PORT}`));
